### ISSUE TITLE
Create Sparkline variation based on Tufte sparkline

### ISSUE THREAD

**Issue by Golodhros** [britecharts/britecharts#100]
We want to have a sparkline that works along with text.
The inspiration for this comes from Tufte's Beautiful Evidence book.

It should have a size related to font sizes, with a probable 'tunning' factor in order to support different font faces.

**Comment by Golodhros** [comment]
![trump_budget_cuts_2019__what_trump_proposed_cutting_in_his_budget_-_washington_post](https://user-images.githubusercontent.com/190833/36521068-a36c1694-1749-11e8-86ca-0c60662519d9.png)

I liked this example from The Washington Post

**Comment by DalerAsrorov** [comment]
This looks cool. I assume this is a still a d3 type `text` element that is tuned by setting font and size?

**Comment by Golodhros** [comment]
Well, not really. It is still the same chart, but as it should work well integrated into text, it would probably benefit from a sizing relative to font size.
That said, this could be challenging as different fonts look different in size for the same font size :(

**Comment by mfdj** [comment]
nitpick: `s/Tuftle/Tufte`
