### ISSUE TITLE
Make charts responsive by default

### ISSUE THREAD

**Issue by Golodhros** [britecharts/britecharts#110]
Right now, in our demos we use a small helper to debounce a listener to the 'resize' event of it's container. This makes it possible to redraw our chart and make it responsive. Any developer would need to do the same to get a responsive chart.

We could easily move that logic inside our charts, making the debounce delay configurable. Or even the method (debounce or throttle).

**Comment by maxmalov** [comment]
I'm curious is it necessary to redraw chart on each resize? I mean scaling is the awesome feature of vector graphics and you can let the browser do the work for you, ex https://css-tricks.com/scale-svg

**Comment by Golodhros** [comment]
Hi maxmalov, thanks for your question!
That's true, SVG scales great, but in the context of D3 visualizations, most of the positioning of the elements is 'absolute' and dependant on the data.

That's why we need to re-render with new data or new dimensions.

**Comment by maxmalov** [comment]
AFAIK, when you specify viewbox for svg element all coordinates within it will be relative to a viewbox. Ex.

```html
<svg width="100px" height="100px" viewBox="0 0 200 200">
  <rect x=10 y=100 width=100 height=2 fill=black/>
</svg>
```

Since viewbox height is larger than actual svg height this rect will be displayed right in the middle. No matter its `y` coordinate is absolute and equals to the actual svg height.

Simple demo: https://jsbin.com/raxomuwene/edit?html,output

**Comment by Golodhros** [comment]
Hi maxmalov, that's a nice trick!

However, I don't think it would scale into the size of elements a regular D3 chart has. Off the top of my head, I don't think this could be applicable to the axis. But maybe I am wrong!

**Comment by maxmalov** [comment]
This example can be also interesting: https://bl.ocks.org/veltman/5cd1ba0b3c623e7b5146

**Comment by maxmalov** [comment]
And yes, you're right about the axis. Still, you can handle them independently, for example, decrease count of ticks: https://blog.webkid.io/responsive-chart-usability-d3/#Prevent-overlapping-of-x-axis-labels

P.S. I just generate ideas and don't force you)

**Comment by Golodhros** [comment]
Wow, that block is pretty neat!! I didn't know this could be done, thanks a lot for the insights!!

Yeah, we are doing some of that kind of tick-magic in our timeAxis helper. It's tricky, and it's not clear to us when it is OK, when it is expected from our code or when are we over-doing it.

Thanks a lot for your comments! Totally, we appreciate this input, and we learned from it!

**Comment by Golodhros** [comment]
Closing this for now due to lack of support by users

**Comment by Golodhros** [comment]
Merged into RC6
