### ISSUE TITLE
Monochromatic Color Palette

### ISSUE THREAD

**Issue by miglesiasEB** [britecharts/britecharts#178]
We want to use different tones of colors for the charts depending on the number of different categories.

## Expected Behavior
We should pick colors depending on the number of color we need in total

## Current Behavior
Right now, we take the first 2 colors of the color palette.

## Possible Solution
Use a new scale that improves contrast

## Context
https://eventbrite.invisionapp.com/d/main#/console/9951901/224614987/preview

**Comment by Golodhros** [comment]
Don't even know what is this. Closing.

**Comment by rwholey-eb** [comment]
lol
