### ISSUE TITLE
New Chart: Create Sankey diagram

### ISSUE THREAD

**Issue by evb-sun** [britecharts/britecharts#193]
Sankey charts graphically illustrates distribution or a flow (example: traffic, money, energy etc) and is a good way for users to digest categorized quantities. A good example of Sankey diagram: http://usafacts.org/the-big-picture?view=spending

Marketing can benefit greatly from this chart and utilize it on mini-sites, marketing landing pages and blogs to offer user an interactive experience; product can also use this to offer organizer insights on user activities during a checkout flow (where do they come from, where do they drop off if the transaction fell through etc.)

Some references:
https://developers.google.com/chart/interactive/docs/gallery/sankey#overview
https://bost.ocks.org/mike/sankey/
http://usafacts.org/the-big-picture?view=revenue

**Comment by Golodhros** [comment]
Bostock's article: https://bost.ocks.org/mike/sankey/

**Comment by rwholey-eb** [comment]
this is dope :)
