### ISSUE TITLE
Typings Definition

### ISSUE THREAD

**Issue by sblack4** [britecharts/britecharts#223]
Hey, 
I'd like to use britecharts but all of my work's libraries are in Typescript.

Is there a plan to produce this?  If not would you guys be interested in shipping the typing definition with the code if I make one?

Thanks!

**Comment by miglesiasEB** [comment]
HI @sblack4 , thanks for your question!

That sounds interesting! We are not familiar with TypeScript, and I was wondering if that type definition could live along regular JS, I guess thats possible?

It shouldn't be hard to do, as we have taken care of specify our types via JSDoc comments.

We would really love to give support to Typescript coders!

**Comment by sblack4** [comment]
Awesome! 

Yeah, it's basically just a `.d.ts` file that lives with your source code.  Your API looks pretty simple so  I should be able to get something going.

Thank you @miglesiasEB!

**Comment by Golodhros** [comment]
I will close this due to lack of interest by other users.

**Comment by uoziod** [comment]
Well, this is actually something that prevents me from starting using the library.

**Comment by Golodhros** [comment]
Hi @uoziod, thanks for the feedback!

We don't use typescript at Eventbrite, so it is highly unlikely that we are going to tackle this anytime soon.

That said, we are open to adding the definitions if someone contributes with them!

Cheers,

**Comment by mikerhyssmith** [comment]
I'd be happy to have a crack at contributing these if you were still interested in adding them ?

**Comment by Golodhros** [comment]
Hi @mikerhyssmith, yes we are!!

It would be cool if we could help developers working with Typescript to use Britecharts!

Thanks a lot!

**Comment by SoerenHenning** [comment]
Are there any updates on this?

**Comment by Golodhros** [comment]
Hi @SoerenHenning, thanks for checking in!

I am not working on this. I am not sure if @mikerhyssmith has anything ready that he could share.

**Comment by Golodhros** [comment]
This feature is being developed on this repository: https://github.com/britecharts/britecharts-typings

Please go there and contribute to help it go faster!

**Comment by Golodhros** [comment]
Added on https://github.com/britecharts/britecharts/pull/878!
