### ISSUE TITLE
Add support for mixed type charts

### ISSUE THREAD

**Issue by qiluo** [britecharts/britecharts#231]
There are cases sometimes that we want to put different types charts in a single chart, e.g. a line chart and a bar chart together, it would be good if we want to build some complex charts.

I'm currently using chart.js which already supports this feature.

**Comment by rwholey-eb** [comment]
This is not currently possible although we have considered it. There was a time when we wanted to show data both as a time series and as an aggregation. Instead, we chose to render two charts on the same page, one below the other. I would be interested to see if there is more interest in this topic! Would you be mind submitting a proposal?

https://github.com/eventbrite/britecharts/labels/proposal

Thanks!

**Comment by qiluo** [comment]
hi @rwholey-eb I'm updated this issue, could you please label it as 'proposal' then? thanks

**Comment by karlAlnebratt** [comment]
Any update on this? Are you thinking of implementing this?
