### ISSUE TITLE
New Chart: Create Heatmap World Map

### ISSUE THREAD

**Issue by miglesiasEB** [britecharts/britecharts#300]
We want to build a world map with a heatmap, like in:

## Expected Behavior
![analytics](https://user-images.githubusercontent.com/9063187/27715627-59eada62-5ced-11e7-8bac-ec3c176da5f6.png)

**Comment by miglesiasEB** [comment]
Related to https://github.com/eventbrite/britecharts/issues/299

**Comment by rickgoud** [comment]
Any progress on this?

**Comment by rwholey-eb** [comment]
@rickgoud  thanks for checking in! I think this would be great addition to britecharts! We base our upcoming projects on the amount of excitement around the proposed features. The more upvotes here the more likely the project will find itself on the immediate roadmap.
