### ISSUE TITLE
Support negative values

### ISSUE THREAD

**Issue by peebeebee** [britecharts/britecharts#338]
Almost all charts should be able to accept and display negative values, except maybe the Donutchart.

## Expected Behavior
When passing in a  negative value, it should go below the x/y-axis. 

## Current Behavior
Right now, we get an error in the console telling us:
Error: <rect> attribute width: A negative value is not valid. 

## Steps to Reproduce (for bugs)
Just pass in a negative value

**Comment by JArmando** [comment]
Part of the fix could be in the `buildScales` function. There is a line setting the min Y axis value that will (in spirit) always assume that the min value is positive:
`let yScaleBottomValue = Math.abs(minY) < 0 ? Math.abs(minY) : 0;`
if you let it be `minY` then it "works". Only problem is that it doesn't handle the ticks correctly.

![image](https://user-images.githubusercontent.com/7327505/37616549-500efb4e-2b7e-11e8-8baa-24b9779f7576.png)

In this example I manually set `yScaleBottomValue  = -100`. I'll try and hack it for my particular case, might dedicate some time to propose a better solution.

**Comment by Golodhros** [comment]
Hi @JArmando, thanks for your comment!

We would love to see your solution to this issue and merge it on Britecharts!

**Comment by Golodhros** [comment]
@cherurg graciously added this feature for the line chart.

We still have a bunch to go though!

**Comment by jkohlin** [comment]
Being new at this. Is there any chance I can have negative values displayed correctly in a line chart today?

**Comment by Golodhros** [comment]
Hi @jkohlin, 
There was an error on the last release build, I will take care of it so that you can use this feature!

**Comment by Golodhros** [comment]
Sorry about the delay.
The fixes are on the latest britecharts release, but we are having issues with the publishing on NPM. I am getting help from our OPS team to figure out what's going on on that publishing pipeline.

**Comment by jkohlin** [comment]
I see. Well no need to hurry for me anymore. I had to move on and find a charting library that had support for this. Thanks anyway for responding.

**Comment by miglesiasEB** [comment]
We managed to publish again on NPM, Britecharts 2.14.4 is live with this change for the line chart!

**Comment by Golodhros** [comment]
@ajdani implemented this for the stacked area chart on #799

**Comment by Golodhros** [comment]
The missing charts are:
- All bar charts (regular, horizontal, stacked and grouped)
- Brush Chart
- Scatter Plot
