### ISSUE TITLE
Choose color for individual items rather than define an overall color scheme

### ISSUE THREAD

**Issue by samuraijane** [britecharts/britecharts#359]
I propose that a property for color be added to ` data ` so we can assign a color to individual items instead of relying on ` .colorSchema() `.

```   
const data = [
  {
    name: 'Milk',
    id: 1,
    quantity: 7,
    percentage: 5,
    color: '#d37f22'
  },
  {
    name: 'Eggs',
    id: 2,
    quantity: 15,
    percentage: 18,
    color: '#b22d76'
  },
  {
    name: 'Bread',
    id: 3,
    quantity: 10,
    percentage: 16,
    color: '#cc29f4'
  }
]
```

**Comment by Golodhros** [comment]
Hi @samuraijane, thanks for the proposal!

This could be a feature yes. In some sense, it would be repetitive with the combination of colorSchema and ordering, but maybe our users feel this is easier.

Let's post this as a proposal and see what our users think about it.
Thanks a lot!

**Comment by miglesiasEB** [comment]
We have been talking about solutions for this, here is our first approach: https://gist.github.com/miglesiasEB/0462752375c53d6271647d647a69684a

**Comment by Drew-FitEpic** [comment]
Has there been any progress on this?  Specifying the colors for a static set of slices regardless of quantity provides the best user experience.  If the colors are always changing based on quantity, consumers of the chart will have to relearn the colors each time quantities change.

**Comment by Golodhros** [comment]
Hi @Drew-FitEpic, sorry for the delay!

We talked over this in https://github.com/eventbrite/britecharts/issues/431 and ended up analyzing the problem in https://gist.github.com/miglesiasEB/0462752375c53d6271647d647a69684a.

There is a proposed solution but we haven't got to it. 

Sorry for the inconvenience!

**Comment by Drew-FitEpic** [comment]
Hello @Golodhros, thank you for the update.  Is this scheduled on a roadmap or are we not likely to see it anytime soon?

**Comment by Golodhros** [comment]
Hi @Drew-FitEpic,
There is no hard deadline but I would love to have this fixed for version 3 of Britecharts.

**Comment by Golodhros** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Colors are not consistent on data filter when trying to implement data toggle](https://trello.com/c/opTaUsUc/44-colors-are-not-consistent-on-data-filter-when-trying-to-implement-data-toggle)

**Comment by amahterian-github** [comment]
Has there been any progress on this?

**Comment by Golodhros** [comment]
Sorry, we haven't done any progress yet.

**Comment by Golodhros** [comment]
Implemented via the .colorMap property on version 3
