### ISSUE TITLE
Support ordinal scales on line and stacked area charts

### ISSUE THREAD

**Issue by ndabAP** [britecharts/britecharts#394]
Hi! It would be nice if the x values are not limited to dates only.

**Comment by Golodhros** [comment]
Hi @ndabAP , thanks for the proposal.

This is a use case that seems to be common, although we haven't find it in our day to day work.
I know @biovisualize is working on something similar in a fork of Britecharts, and we are willing to port that over soon. 

Some questions that come to my mind would be:
- Should we keep the two scales inside the charts or should we extract them so it's another configuration of the chart?
- In case we keep them inside, should we automatically detect the right scales?

**Comment by ndabAP** [comment]
I just discovered this chart library while I was looking for an easy to use, nice looking set of charts. I consider to use it for my project but the date limitation is the only thing that's blocking me. 

Regarding scales: Since you can use most charts out of the box, automated scale detection would be something I expect.

**Comment by Golodhros** [comment]
Thanks for the feedback @ndabAP !

I am curious about your use case, what kind of data do you need to chart that has a line/stacked area for ordinal data? I guess I would try a bar chart, but maybe is not a good choice?

**Comment by ndabAP** [comment]
It's completely user driven. My users can compose charts and therefore there should be no limitation. But when I speak for myself, I'm a runner and I love to see my distance and duration visualized. 

Thanks a lot for taking the time and the investigation.

**Comment by mmartimo** [comment]
Also for us, I need to compare hourly data week over week or month over month...  this is most easily done by stacking them on the line chart so you can see which week/line deviates from the rest.  

Currently it is weird to set them all to the first week of the year and then try to hide the axis.  :(

**Comment by SoerenHenning** [comment]
Is there anything new about it? I would like to contribute in implementing this, but it would be good to know if there was already done some work on this.

**Comment by Golodhros** [comment]
Hi @SoerenHenning,

Nobody is working on this at the moment. We are in the middle of a general build system update and refactor into ES modules.

Please, feel free to investigate this! If you could write something about your approach here it would be ideal. We could discuss it before you write any code.

Thanks for your contribution!!
