### ISSUE TITLE
Colors are not consistent on data filter when trying to implement data toggle

### ISSUE THREAD

**Issue by dalerasrorov-eb** [britecharts/britecharts#431]
I created a `customClick` event and on that event, I am attaching a custom class that adds a styling to the legend that was clicked. Was basically trying to implement a feature for this issue https://github.com/eventbrite/britecharts/issues/220

        let filteredData;
        legendChart.on('customClick', function(d) {
            filteredData = filteredData ? filteredData : dataset;
            filteredData = filteredData.filter(dataPoint => dataPoint.id !== d.id);

            donutContainer.datum(filteredData).call(donutChart);
        });

## Expected Behavior
When I re-render the donut chart using the filtered data, the colors rendered in the donut (or any other) chart should stay the same and consistent with the connected legend chart.

## Current Behavior
When I re-render the donut chart using the filtered data, the colors rendered in the donut chart for each data point is different from before the filter. The toggle feature, if implemented, will behave the same way for all charts. 

## Possible Solution
Allow the user to add a color mapping to the data or have a separate color mapping function that maps random colors to each data point and uses that mapping through-ought the code.

## Steps to Reproduce (for bugs)
1. Create a custom event for the legend (`customClick`, for example, or `customHover`)
2. On click, filter the data of the chart that is connected to it (like donut, bar or line charts)
3. In the demo, observe that the original color in donut chart is different from legend chart (legend has the original color since its data stays the same).

## Context
Tried to add a new feature to legend chart to solve this issue https://github.com/eventbrite/britecharts/issues/220

**Comment by miglesiasEB** [comment]
Here is the discussion: https://gist.github.com/miglesiasEB/0462752375c53d6271647d647a69684a

**Comment by cedseat** [comment]
When this feature will be availlable?

**Comment by Golodhros** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Colors are not consistent on data filter when trying to implement data toggle](https://trello.com/c/opTaUsUc/44-colors-are-not-consistent-on-data-filter-when-trying-to-implement-data-toggle)

**Comment by Golodhros** [comment]
This is a step in the right direction: https://github.com/britecharts/britecharts/pull/875
We still need to add colorMap to the donut and other charts though.
