### ISSUE TITLE
Grouped Bar Chart's colorSchema's color order is not consistent with appearance

### ISSUE THREAD

**Issue by Dieber** [britecharts/britecharts#454]
## Current Behavior

the Legends color is right, but Bars' color isn't sort by the sequence of colorSchema

Screenshots

https://i.loli.net/2017/12/25/5a40cc924c152.png

there is a testdata below:

test data:

colorSchema: ['#3399ff', '#54cd72', '#fdd210']

data: [
          {
            group: 'Direct',
            name: 'Direct1',
            value: 3,
            date: '2011-01-05'
          },
          {
            group: 'Eventbrite',
            name: 'Eventbrite1',
            value: 23,
            date: '2011-01-05'
          },
          {
            group: 'Email',
            name: 'Email1',
            value: 10,
            date: '2011-01-05'
          },
          {
            group: 'Direct',
            name: 'Direct2',
            value: 10,
            date: '2011-01-06'
          },
          {
            group: 'Eventbrite',
            name: 'Eventbrite2',
            value: 16,
            date: '2011-01-06'
          },
          {
            group: 'Email',
            name: 'Email2',
            value: 20,
            date: '2011-01-06'
          },
          {
            group: 'Direct',
            name: 'Direct3',
            value: 16,
            date: '2011-01-07'
          },
          {
            group: 'Eventbrite',
            name: 'Eventbrite3',
            value: 10,
            date: '2011-01-07'
          },
          {
            group: 'Email',
            name: 'Email3',
            value: 26,
            date: '2011-01-07'
          },
          {
            group: 'Direct',
            name: 'Direct4',
            value: 23,
            date: '2011-01-08'
          },
          {
            group: 'Eventbrite',
            name: 'Eventbrite4',
            value: 4,
            date: '2011-01-08'
          },
          {
            group: 'Email',
            name: 'Email4',
            value: 33,
            date: '2011-01-08'
          }
        ]

**Comment by Golodhros** [comment]
Hi @Dieber, thanks for the issue!
That looks like a bug, yes. Could you create a codepen with this? It would be really helpful to reproduce it in order to fix it.
Thanks a lot!

**Comment by Dieber** [comment]
@Golodhros 
Here it is
https://codepen.io/Dieber/pen/Lexozd

**Comment by Golodhros** [comment]
Hi @Dieber, thanks for taking the time to reproduce the bug!
Yeah, that should be aligned, it is a bug.

Thanks a lot!

**Comment by faulkiebear** [comment]
I am also having this problem with inconsistent grouped bar colouring. When is this expected to be fixed? And is there a workaround? At the moment we are trying to just entirely rerender the graph and flip the colour schema in the process. Is this likely to work or will this bug make this approach ineffective? 
i seem to be using "version": "2.5.0".

**Comment by Golodhros** [comment]
Hi @faulkiebear ,

Sorry to hear you are experiencing this too. We cannot give you an estimate, but we will try to prioritize this bug.
What you say seems like a good workaround.

**Comment by dalerasrorov-eb** [comment]
@Dieber if you transform the data you provided to this:
```
[
        {
            "stack": "Direct",
            "name": "Direct1",
            "views": 3,
            "date": "2011-01-05"
        },
        {
            "stack": "Eventbrite",
            "name": "Eventbrite1",
            "views": 23,
            "date": "2011-01-05"
        },
        {
            "stack": "Email",
            "name": "Email1",
            "views": 10,
            "date": "2011-01-05"
        },
        {
            "stack": "Direct",
            "name": "Direct2",
            "views": 10,
            "date": "2011-01-06"
        },
        {
            "stack": "Eventbrite",
            "name": "Eventbrite2",
            "views": 16,
            "date": "2011-01-06"
        },
        {
            "stack": "Email",
            "name": "Email2",
            "views": 20,
            "date": "2011-01-06"
        },
        {
            "stack": "Direct",
            "name": "Direct3",
            "views": 16,
            "date": "2011-01-07"
        },
        {
            "stack": "Eventbrite",
            "name": "Eventbrite3",
            "views": 10,
            "date": "2011-01-07"
        },
        {
            "stack": "Email",
            "name": "Email3",
            "views": 26,
            "date": "2011-01-07"
        },
        {
            "stack": "Direct",
            "name": "Direct4",
            "views": 23,
            "date": "2011-01-08"
        },
        {
            "stack": "Eventbrite",
            "name": "Eventbrite4",
            "views": 4,
            "date": "2011-01-08"
        },
        {
            "stack": "Email",
            "name": "Email4",
            "views": 33,
            "date": "2011-01-08"
        }
    ]
```
I can't reproduce this bug if I follow this format instead.

**Comment by amahterian-github** [comment]
I'm also experiencing this with StackedBarChart. The colors don't sync up with the color order of the Legend.

<img width="779" alt="Screen Shot 2019-12-29 at 6 03 43 PM" src="https://user-images.githubusercontent.com/8904305/71563909-951d2480-2a65-11ea-8b88-5f527df6ade1.png">

**Comment by Golodhros** [comment]
Hi @amahterian-github,

True, we have a plan to fix this but we haven't got to implement it yet.
A workaround, for now, would be to change the ordering of the data as you pass it to the legend so that it matches. Hacky, I know. Sorry for the inconvenience!

**Comment by Golodhros** [comment]
This will be solved with https://github.com/britecharts/britecharts/pull/875
