### ISSUE TITLE
Add support for Chart Annotations 

### ISSUE THREAD

**Issue by tamascsaba** [britecharts/britecharts#473]
I would like to add a vertical line in y asis to (spakrline) chart. Is it any possible solution?

**Comment by Golodhros** [comment]
Hi @tamascsaba, thanks for opening the issue!

Out of curiosity, I would like to know the use case. Do you need the y-axis due to a purely aesthetic reason? Would a line chart work for you? 

Thanks!

**Comment by tamascsaba** [comment]
Hi @Golodhros, I want to use britecharts to create this chart (attached picture). The sparkline chart is good, but i want to add an exta line to the chart, as you can see "Start of Session ..."
![chart](https://user-images.githubusercontent.com/3479963/34712791-69ca0eba-f524-11e7-885c-4fed7b7dfbd1.png)

**Comment by Golodhros** [comment]
Hi @tamascsaba,
I see what you mean. That would be a chart annotation. Right now we don't support this feature, although we would love to do it! 
I am going to transform this ticket into a feature proposal, but I am afraid I can't give you an estimate of when this will be ready.

Thanks!
