### ISSUE TITLE
Remove limit of 8 bars for Stacked Bar animation

### ISSUE THREAD

**Issue by nediljko** [britecharts/britecharts#475]

**Comment by Golodhros** [comment]
Hi @nediljko,
I am not sure to understand the question. In what context are we limiting the number of animations? Which chart are you using?

**Comment by nediljko** [comment]
I'm using stacked bar chart, and the maxBarNumber in stacked-bar.js is set to 8.
Now my task requires around 20 bars and if I enable animations only 7 bars will be drawn but if I disable animations every bar will be drawn.
So I was thinking maybe maxBarNumber has limits only when animations are enabled.

**Comment by Golodhros** [comment]
Hi @nediljko,
Checking the code it seems that 8 is an arbitrary number set to pace the animations.
You are right in that this number doesn't have any importance when not using animations.

I will transform this ticket into an enhancement proposal, so we could eventually remove that limit of 8 animated bars.

Thanks a lot!
