### ISSUE TITLE
Remove 'label' properties from charts

### ISSUE THREAD

**Issue by Golodhros** [britecharts/britecharts#482]
## Background
Since the beginning of Britecharts, we have included options to change how we look for the values we need on the passed in data. This options (nameLabel and valueLabel in the (Bar)[http://eventbrite.github.io/britecharts/module-Bar.html]) are there in order to make it easy to use Britecharts.

For non-tech savvy users, those classes can help them get started with Britecharts almost immediately. They let them use info that comes from third party sources directly, without having to code anything and making the library more accessible and flexible.

On the other side, from the point of view of engineering and API correctness, they are non-ideal. We could think that the data schema should be fixed, and our users would need to do the data transformations they need to follow that schema.

With Britecharts, we have tried to create a library that works both for designers and non technical people and for d3 developers. I don't think choosing to remove this options or keeping them will change that, but it is true that we don't know where the bulk our users are in those two groups. 

## Questions
Do you hate those options? - we could remove it in the next major release
Are you confused by them? - it could be solved by better docs or better naming
What are our users tech level? - We could run a survey trying to get more info about how people use Britecharts 

## Considerations
- Removing this options would need a major release, as they will be a breaking change

## Next Steps
I would love to hear the opinion of as many people possible, both contributors and regular users.

**Comment by mrbongiolo** [comment]
I vote for removing them, I do not hate it, but find it quite confusing.

As suggestion: what about a `dataMapper`? Something like: `{ name: 'weirdName', value: 'value' }`. Or would it still be confusing to non-tech users?

**Comment by Golodhros** [comment]
You mean to remove all the label options and instead placing a dataMapper option?

It would look like:
```
barChart
  .widht(200)
  .dataMapper({
    name: 'weirdName',
    value: 'value'
  })
```
right?

If that's the case, I think is actually better. It is more clear what it is doing, and also it would only take one getter/setter to deal with up to three 'labels' as we do now in some charts. With proper documentation this will be clear.

Still a breaking change, so if everybody prefers to get rid of them, we could avoid it.

**Comment by mrbongiolo** [comment]
@Golodhros Yes, just like that.

**Comment by jchen-eb** [comment]
IMO it would be best if we forced them to give the data in a fixed schema, and drop the concept of nameLabel and valueLabel. I think we aren't giving users enough credit to transform the data themselves. In fact, I think it's more confusing to tell the user that "hey you can pass data in any format you want, as long as you remember to use nameLabel and valueLabel to inform us of the shape of your data." 

I think the dataMapper is a reasonable solution, but if the user is savvy enough to understand the dataMapper, I don't think it's any harder to ask them to transform the data themselves. The dataMapper concept is already so similar to JS Array.prototype.map, so why not just use the one that everyone knows instead of introducing a new API?

**Comment by dalerasrorov-eb** [comment]
I agree with @jchen-eb, removing the options would make the most sense. Allowing user to provide a fixed set of data will help us manipulate the colors better as well (for example, on data toggle). As already mentioned `Array.prototype.map` is already efficient and reliable enough to use it. Also, seems like the original way is confusing for quite a few users, so removing it might be even encouraged.

**Comment by Golodhros** [comment]
Hi @iamkk11, the bar chart doesn't support labels at this moment.
Let me create a feature proposal for it: https://github.com/eventbrite/britecharts/issues/629

**Comment by Golodhros** [comment]
We started the deprecation process on https://github.com/britecharts/britecharts/issues/482

Not sure if we should keep the notices all over the Version 3, or just have them for the RC process and remove them on version 3.

Thoughts?
