### ISSUE TITLE
GroupedBar chart doesnt allow .xAxisFormat() or equivalent to enable only printing every nth x axis label

### ISSUE THREAD

**Issue by faulkiebear** [britecharts/britecharts#533]
![image](https://user-images.githubusercontent.com/19652111/36679111-54061446-1b0a-11e8-86e4-a12de3b21359.png)

I know this only makes sense for continuous/chronological x data but I want to display 2 one hour data sets against each other and the labels bunch up pretty fast. 

So if i could draw only every 10th label, for example, that'd be really handy. 

A possible solution could be for me to use a graph better designed for displaying continuous data like a line graph but i already have 5 other resolutions working sensibly with the groupedbar and i don't want to change for just one of the options. 

I could also add another preprocessing step to group the data before rendering in the chart but that wouldn't look as nice as the solution i'm proposing.

**Comment by Golodhros** [comment]
Hi @faulkiebear , thanks for the issue!

Wow, that is a nice looking chart! I never thought the grouped bar chart could be used to do something like that. It is awesome!

What you propose is definitely an interesting feature. We currently don't support it even in our time-series-based charts (line and stacked area), but your use case demonstrates that there could be room for it.

Off the top of my head, I am not sure how we could implement it, but I am sure a deeper research could shed some light on it.

Thanks again!

**Comment by kendrive** [comment]
Faced a similar problem. As a solution I see in the use of Brush Chart. However, I did not find an example of using it with Grouped Bar Chart.

**Comment by Golodhros** [comment]
Won't do for now.
