### ISSUE TITLE
Stacked area empty state needs to be cleared on page resize

### ISSUE THREAD

**Issue by amber-eb** [britecharts/britecharts#544]
## Expected Behavior
- Line chart renders its empty state on page load
- On page resize, the previous empty state is cleared and a new, appropriately sized empty state is added.

## Current Behavior
On page resize, new empty states keep being added to the DOM:
![screen shot 2018-03-06 at 3 36 37 pm](https://user-images.githubusercontent.com/33266899/37065053-3e5b3c66-2154-11e8-9f42-5cdcc64475fd.png)
This can result in visual glitches:
![screen shot 2018-03-06 at 3 36 17 pm](https://user-images.githubusercontent.com/33266899/37065062-45e5f192-2154-11e8-907e-7cd641d257d9.png)

## Possible Solution
Clear the previous empty state elements when rendering on page resize

## Steps to Reproduce (for bugs)
1. Render a line chart with an empty state (no data)
2. Resize the page
3. Search the markup for "empty-data-line" and observe one per page resize

**Comment by dalerasrorov-eb** [comment]
Wasn't able to reproduce it. Is there any additional condition? Browser?
