### ISSUE TITLE
Add `dist/` folder to the github releases

### ISSUE THREAD

**Issue by hisnameisjimmy** [britecharts/britecharts#546]
It would be great for setting up simple projects, where you don't want 3rd party CDN dependencies or to get in bed with NPM et al. Simple pages where someone can literally just copy/paste the code and get started would be amazing.

## Expected Behavior
There should be a dist folder, or at the very least some demo pages with relative-linked static assets so that someone can start hacking away quickly without setting up a package.json and getting involved with our modern, flexible, and incredible, but often overly complicated setups for starting a project. 

## Current Behavior
No dist folder, have to either save CDN files or install the project locally, then pick out the resulting dist files. 

## Possible Solution
Make a dist folder part of the releases. Make the demo pages self-contained and not reliant on current piecemeal structure.

## Context
Installing and debugging this took much longer than it would have if there were very simple, understandable examples. The Codepens helped significantly, but even then link libraries in their 'settings'. Self contained HTML files where you could visually and cleanly view the source and understand the structure immediately are really nice.

**Comment by Golodhros** [comment]
Hi @hisnameisjimmy , thanks for the issue!

You are right, the dist/ folder should be part of the packed release zip. We should change that.

I am surprised that you didn't want to use the CDN links though, I was assuming that those cover the use case you are describing.

Regarding the demo pages, we are also not super happy about them. We had another user talking about it on https://github.com/eventbrite/britecharts/issues/296. For us it has been a bit disheartening the status of the JS-based documentation projects (most of them abandoned or imcomplete). Managing a lot of Codepen Pens and keep them up to date has been a challenge too. We will be iterating over this, hope we can get somewhere soon!

Thanks for your analysis!

**Comment by hisnameisjimmy** [comment]
@Golodhros Part of the issue is that different demos/examples use different ways of referencing things. (Apologies in advance for this long screed)

Some of them use Require (In project demos), some use CDN (codepen and jsbin). If someone who has never used Require wants to jump in and learn from the demos, they're going to see code that is confusing. They're not going to understand that if you pull down the full d3 minified js, that you won't also need to reference d3Selection through Require as its included in the full minified d3 (they need `d3.select`, instead of `d3Selection.select`). They also might not understand the semi-hidden library references in the codepens (The fact that you have to go to settings, etc). I did love the codepens, because they were really simplified and standalone, but it would be even better if these existed in their own html files.

In my project, I did end up using the CDN links, but ultimately I did it to get a clear idea of how a simple project would be to setup. I then saved those files locally, and called them in with require. I had to significantly alter example code to fit in with how I was setting things up, which is not super surprising, but it took a fair amount of debugging before I got it working. 

A lot of it was silly stuff, like in some of your examples you call the following like this:

```
barChart = bar(),
tooltip = miniTooltip(),
```

Whereas in others, you do the following:

```
barChart = britecharts.bar(),
tooltip = britecharts.miniTooltip(),
```

I had to do the second option, the first had me mucking around in the console for errors initially.

I would also love more example JSON data. There are references to using data, but I had to mess around with some, specifically `dataByTopic`, which took me jumping around trying to find a good example of it. The references in globals felt a bit incomplete.

When it comes to jumping in, having just straight up understandable, not 'clever' files is the easiest way to gain initial comprehension. I would love just a set of static html files, all referencing a clear dist directory with the bundled files would be amazing. That lets me know what it's like when everything is very straight forward: One CSS file with all styles, One JS file with all necessary JS for all situations, dependencies for that version are included, separate or inline JSON data files (instead of using generated data). I then have the option of going more modular if I desire in the future, but at least these initial examples are clear as day.

**Comment by Golodhros** [comment]
Totally understand!
We have been planning to create a tutorial page for the whole installation and the myriad of ways we can do it. It seems we should prioritize it.

What you suggest for the demos makes a lot of sense. We will take that into account when creating the new demo pages.

Thanks a lot for your feedback, is super important to us!

**Comment by Golodhros** [comment]
I have been looking around, and couldn't find a good way of doing this.
I will close it for now.
