### ISSUE TITLE
Better Documentation for ToolTip

### ISSUE THREAD

**Issue by hisnameisjimmy** [britecharts/britecharts#548]
I was trying to adjust the offSet for ToolTip and had to read the source to understand how to feed it values: [ToolTip Source](https://eventbrite.github.io/britecharts/tooltip.js.html)

I can get it to adjust the y, but not the x.

Here's an example: http://jsbin.com/gefibas/edit?html,js,output

```
            lineTooltip
                .valueLabel('value')
                .tooltipOffset({
                    y: 20,
                    x: -10
                })
                .title('Check-ins');

```

I'd prefer to use miniTooltip, but I'm not able to get it to render for line graphs (not even sure it's supported). 

## Expected Behavior
Both X and Y should adjust position

## Current Behavior
Only Y seems to adjust

## Possible Solution
Better documentation around this would be nice, but the ultimate solutions is me understanding JScript syntax better.

## Steps to Reproduce (for bugs)
http://jsbin.com/gefibas/edit?html,js,output

## Context
Adjusting tooltip position is useful in areas where there is limited space, as exists in our application. Using the miniToolTip here would also be nice, but the documentation is limited.

**Comment by Golodhros** [comment]
Hi @hisnameisjimmy, thanks for the well-crafted issue!

I totally get it, working with that tooltip is sometimes challenging even for me. You are right about the miniTooltip, at this moment is not supported in the line or stacked area charts.

Our plan in the short term is to merge the functionality of the tooltip into the mini-tooltip, and get ride of it entirely (probably changing the name to tooltip). Here is the ticket https://github.com/eventbrite/britecharts/issues/113.

I hope we can get to it soon!

**Comment by Golodhros** [comment]
related to #113

**Comment by Golodhros** [comment]
Will close as part of #113
