### ISSUE TITLE
Donut-pie chart combined

### ISSUE THREAD

**Issue by jhuesos** [britecharts/britecharts#553]
## Expected Behavior
It would be nice to be able to have a combine donut-pie chart option.

Something like: https://bl.ocks.org/SpaceActuary/0e20fb7d21cce9ec1302

![2018-03-12_15-03-50](https://user-images.githubusercontent.com/339609/37288058-96e238e2-2606-11e8-92b1-64206ad99b71.png)

Another example:

[https://www.highcharts.com/demo/pie-donut](https://www.highcharts.com/demo/pie-donut)

## Current Behavior
At this moment you can't build this type of chart (as far as I know).

## Possible Solution
I attached an example build with D3, so it is possible. It would be a matter of coming up with a proper API and data structure.

## Context
We use this chart to represent 2 levels of data, like in the example from Highcharts: where you can see the usage per product and then the combined value per category.

**Comment by Golodhros** [comment]
Hi @jhuesos, thanks for the proposal!

**Comment by Golodhros** [comment]
Won't do for now.
