### ISSUE TITLE
Fix Line chart animation

### ISSUE THREAD

**Issue by hisnameisjimmy** [britecharts/britecharts#554]
Line chart animation is a bit awkward on screen compared to stacked area chart. Line chart paints left to right, wheras the stacked chart does a cool 'rise from the bottom' animation that is very attractive.

An example:

![line-paint2](https://user-images.githubusercontent.com/740373/37293144-ce710caa-2612-11e8-9b19-174f8b0b942f.gif)

## Expected Behavior
The animation should be fluid, not a left-to-right paint

## Current Behavior
It just does a left-to-right paint

## Possible Solution
Imitate the animations currently produced on stacked line charts

**Comment by Golodhros** [comment]
Hi @hisnameisjimmy, thanks for the request!

Yeah, I agree with you. We are looking into adding the same kind of animation to the line chart. I am not sure when though.

Related to this is https://github.com/eventbrite/britecharts/issues/114

**Comment by rajeshmr82** [comment]
@Golodhros Does something like this make sense?
![linechart](https://user-images.githubusercontent.com/10022651/136968875-123c445b-8999-4846-970c-981b47a6d01e.gif)

**Comment by rajeshmr82** [comment]
> 
> 
> > @Golodhros Does something like this make sense? ![linechart](https://user-images.githubusercontent.com/10022651/136968875-123c445b-8999-4846-970c-981b47a6d01e.gif)
> 
> I does look good on the left side, but I see some lines starting from the right that seem confusing. I think we want them to appear from left to right only.
> 
> It looks good though! Are you applying an opacity animation to the line itself?

Lines starting from the right can be addressed.
![linechart1](https://user-images.githubusercontent.com/10022651/137069526-5fac16cf-cd3a-4301-901b-d18189b2225c.gif)

Yes, I am re-tracing the line using transition.

I have created a PR (#945) for this. Please review.
