### ISSUE TITLE
Support for crossfilter

### ISSUE THREAD

**Issue by patrickcate** [britecharts/britecharts#564]
Does britecharts have support for [crossfilter](https://github.com/crossfilter/crossfilter), similar to [DC.js](https://dc-js.github.io/dc.js/) ? If not, are there any plans to add support?

**Comment by DalerAsrorov** [comment]
@patrickcate thanks for the question! I haven't tried using `crossfilter` with Britecharts yet so not exactly sure if it does. The library is primarily used for handling large datasets so I can imagine . This would be a nice addition to the charts (if it is not compatible, should be checked). Will mark this issue as proposal. We currently have multiple things to do before this but will look into it. Could you share your use case?

**Comment by Golodhros** [comment]
Closing for now, unless there is more requests going forward.
