### ISSUE TITLE
Decide a thorough strategy for Bullet chart tooltip

### ISSUE THREAD

**Issue by DalerAsrorov** [britecharts/britecharts#604]
The way data is passed to tooltip on hover is implemented differently in some charts (Scatter Plot vs Stacked Area, and others). For `Bullet` chart, it would be a good idea to choose a proper strategy to expose bullet chart's data to the user `onMouseOver` and other mouse/touch events.

**Comment by Golodhros** [comment]
Yeah, let's sync about this when I am back!

**Comment by dalerasrorov-eb** [comment]
Example: http://dimplejs.org/advanced_examples_viewer.html?id=advanced_bullet
