### ISSUE TITLE
Stacked Donut Chart

### ISSUE THREAD

**Issue by thom7kick** [britecharts/britecharts#605]
I have one question on how can we implement a stacked donut chart as the screenshot below
![04_radial](https://user-images.githubusercontent.com/9592529/39863109-6571f2b8-544e-11e8-817a-3c11269342d6.png)

## my environment
* MacOs sierra:
* Chrome v 66

**Comment by Golodhros** [comment]
Hi @thom7kick, thanks for the issue!

At this time this is not possible. We could make this a proposal and see how wide is the support for a chart of this characteristics.

**Comment by thom7kick** [comment]
[Here is a starter code](https://codepen.io/beeyen/pen/GCukD?editors=1010).

**Comment by dalerasrorov-eb** [comment]
This is a nice example @thom7kick ! Thanks a lot

**Comment by Golodhros** [comment]
Won't do for now.
