### ISSUE TITLE
Make Sandbox part of documentation

### ISSUE THREAD

**Issue by dalerasrorov-eb** [britecharts/britecharts#617]
@ryanwholey asked about the sandbox today and it reminded me. I use Sandbox to reproduce some bugs changing the dataset and charts. It would be cool to include them in official documentation.

## Expected Behavior

Sandbox should be available in official documentation

## Current Behavior

Sandbox available only on local machine if you run `yarn sandbox`

## Possible Solution

Add Sandbox to deployment build and reference the Sandbox page from navigation bar in official documentation.

## Context

Often times we want to reproduce bugs and instead of asking people to create codepens, why not have them reproduce things in sandbox?

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version:
* Link to your project or codepen:

**Comment by Golodhros** [comment]
+2 
It would be an awesome tool to provide our users with!

**Comment by Golodhros** [comment]
It seems that adding it to the docs as they are will be a big headache.
In https://github.com/eventbrite/britecharts/pull/719 I have updated the styles and the code, so I think we could promote it among the contributors.

We should probably tackle the rework of the docs if we want to expose it to the users in general.

**Comment by Golodhros** [comment]
I think the need for a public sandbox would be deprecated with the new Storybook demos on our new website.
