### ISSUE TITLE
Tooltip with dynamic title based on x-axis label

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [britecharts/britecharts#623]
I'm working on a stacked bar chart with a categorical x-axis which is not time based. I'd like to have the tooltip title reflect which category is being viewed.

![image](https://user-images.githubusercontent.com/8518288/41365883-d72729d2-6ef7-11e8-8c73-051de750c7eb.png)

## Expected Behavior
[codepen](https://codepen.io/constantinoschillebeeckx/pen/WyOJOW)

## Current Behavior
Title is set with a string.

## Possible Solution
I'm getting around this issue by doing something like:
``` js
toolTip.on('customMouseMove', function(dataPoint, topicColorMap, x,y) {
        chartTooltip.title(dataPoint.key); // <-- boom
        chartTooltip.update(dataPoint, topicColorMap, x, y);
      })
```
I'm wondering if this is the best way of doing things since the title will repeatedly get updated even if it doesn't need to be.

**Comment by Golodhros** [comment]
Hi @ConstantinoSchillebeeckx, thanks for creating this issue!

Your feature request makes sense. That tooltip was thought originally for doing only time series charts, so it is not ideal for this chart.

Your workaround is great! I won't care a lot about doing it, as it does what we would do anyway. In the medium term, the Tooltip Rework [issue](https://github.com/eventbrite/britecharts/issues/113) should tackle this problem.

Thanks a lot!

**Comment by Golodhros** [comment]
This is actually the way to do this.
