### ISSUE TITLE
Vuejs bindings

### ISSUE THREAD

**Issue by laurentdebricon** [britecharts/britecharts#625]
How do you deal with integrating britecharts in Vuejs ?

I'm thinking of something like this 
https://dotnetage.github.io/vue-nvd3/#/examples/bar-chart

Has anyone already made this ?

Best regards

**Comment by dalerasrorov-eb** [comment]
Hi @laurentdebricon ! Thanks for the question. There was a talk on having Vue bindings. We are currently not working on that but it is in plans. Right now the highest priority binding is the React binding of Britecharts.
For Vue charts to work we would still have to create a component for each chart:
https://github.com/DotNetAge/vue-nvd3/tree/master/src/components
This is similar to what we are doing right now for React wrapper:
https://github.com/eventbrite/britecharts-react/tree/master/src/charts

After react wrapper, tackling Vue seems like a reasonable goal. Besides that, if someone else wants to do it, that would be also great!

**Comment by Golodhros** [comment]
Hi @laurentdebricon, thanks for the issue.

As Daler commented, we would love to have a Vue version of Britecharts too, but we won't have bandwidth anytime soon.

I just want to add that in theory, you should be able to leverage the chart wrappers we created for Britecharts-React, like this one: https://github.com/eventbrite/britecharts-react/blob/master/src/charts/bar/barChart.js

**Comment by laurentdebricon** [comment]
Have you seen this project ?
https://github.com/chryb/vue-c3/blob/master/src/VueC3.vue
it's just 65 lines, a cute handy little wrapper, and animation works, but for C3

**Comment by Golodhros** [comment]
Hi @laurentdebricon, thanks for the reference!

That indeed seems like a great jumpstart for this project!

I wanted to give you a heads up though, as even if having a Vue wrapper is an aspiration of us, it doesn't seem that it will happen anytime soon. First, we want to wrap up and release Britecharts-React, then release Britecharts 3.0 and only then we would tackle Britecharts-Vue.

Unless we find a lot of contributors out of the blue, I think this will probably take us the rest of 2018 to finish it.

**Comment by laurentdebricon** [comment]
Hello, thanks @Golodhros , i managed to make a bar chart, dependant of britecharts-react :)

BarBright.vue
```
<template>
	<div></div>
</template>
<script>
import barChart from 'britecharts/dist/umd/bar.min';
import { select } from 'd3-selection';
import { validateConfiguration, validateContainer } from 'britecharts-react/src/charts/helpers/validation';
import optimizedResize from 'britecharts-react/src/charts/helpers/optimizedResize';

import { applyConfiguration } from 'britecharts-react/src/charts/helpers/configuration';

import { bar as barLoadingState } from 'britecharts/dist/umd/loading.min';

export default {
	name: 'bar-bright',
	props: ["data", "configuration", "loading"],
	data() {
		return {
			$chart: null
		}
	},
	watch: {
		data: function(newVal, oldVal) {
			const container = select(this.$el);
			const chart = this.$chart;

			validateContainer(container);
			validateConfiguration(chart, this.configuration);

			container.datum(newVal).call(chart);
		},
		loading: function(newVal, oldVal) {
			this.beforeDestroy();
			this.mounted();
		}
	},
	methods: {
		resize: function() {
			if (!this.loading) {
				this.configuration.width = this.$el.clientWidth;
				const container = select(this.$el);

				container.call(applyConfiguration(this.$chart, this.configuration));
			}
		}
	},
	mounted() {
		if (this.loading) {
			select(this.$el).html(barLoadingState);
		} else {

			const container = select(this.$el);
			const chart = barChart();


			validateContainer(container);
			validateConfiguration(chart, this.configuration);

			container.datum(this.data).call(applyConfiguration(chart, this.configuration));

			this.$chart = chart;

			optimizedResize.addHorizontalMain(this.resize.bind(this));

		}

	},
	beforeDestroy() {
		optimizedResize.clearAll();
	}
}

</script>

```

You use it like that : 

```
<bar-bright :configuration="{isHorizontal: false}" :data="[{value: 1,name: 'glittering'},{value: 1,name: 'luminous'}]" :loading="false"></bar-bright>
```

**Comment by Golodhros** [comment]
Wow!!! This is so awesome @laurentdebricon !!

It is also great that you could do it using Britecharts-React components, even the validations!

Thanks a lot for this!
