### ISSUE TITLE
Allow Access to all chart's d3 scales and axes

### ISSUE THREAD

**Issue by dswamy** [britecharts/britecharts#632]
Provide access to x & y scales and axes for customization

## Expected Behavior

I would like to have access to xScales to customize positioning of certain labels (e.g. bar top label center align)

## Current Behavior

scales and axes are private and inaccessible for extension/customization

## Possible Solution

Expose the xScale and yScale from chart getters

## Context

Exposing scales and axes will allow more customizations in our charts.

**Comment by DalerAsrorov** [comment]
Hi @dswamy, thanks for creating the issue. The idea of abstracting scales and axis was necessary to make building nice charts easier with this framework. What kind of control are you looking for? Could you give more details or description?

**Comment by dswamy** [comment]
Hi Daler -
I am looking to access xScale, yScale through chart API so I can render or reposition certain elements.
I have been using nvd3 chart library for last 3 years and it provides very similar reusable charts API like britecharts. However, it also provides access to underlying scales, axes etc so you can customize charts further.

See API here
http://nvd3-community.github.io/nvd3/examples/documentation.html#discreteBar

use-case 1
-------------
I have bar chart data for 6 months (Jan 2018 to Jun 2018) displayed using 6 bars. I like to customize my bar chart by adding dotted vertical line for Mar 2018 to highlight some event. For this, i need access to xAxis scale() function to get x-coordinate for axis. 

e.g. in nvd3 library
const barChart = nv.models.barChart().options({margin:...})
d3.select('.chart').datum(data).call(barChart)

const xScale = barChart.xScale(); //get access to d3 x-axis scale
const xPos = xScale(new Date(2018, 2, 1)); //get xPos for Mar 2018 from scale

now, using xPos. I can render a new svg dotted line at the xPos.

use case 2
-----------
britecharts bar chart is left aligning the bar label (value shown at top of the bar). I like to center align. If I have access to xScale - I can reposition the labels by calculating correct offset.

nvd3 exposes xScale, xDomain, xRange and many other properties through the chart function so you can further customize chart. Looking for something similar here in britecharts

barChart = new BarChart()
                .colorSchema([barColor])
                .betweenBarsPadding(0.5)
                .margin({left: 10})

const xScale = barChart.xScale(); //MISSING. need this API to get xScale
const yScale = barChart.yScale(); //MISSING. need this API to get yScale

nvd3 reference (see section - expose public variables)
https://github.com/nvd3-community/nvd3/blob/master/src/models/discreteBarChart.js
https://github.com/nvd3-community/nvd3/blob/master/src/models/discreteBar.js

Let me know if further questions

Thank you,

Deepak

**Comment by Golodhros** [comment]
Hi @dswamy, thanks for opening the issue and for the detailed use cases!

I understand your use cases and see how exposing the scales will be useful to allow those extra customizations.

At the same time, making the axes public is not in the level of abstraction that we originally envisioned for Britecharts. It will be definitely useful for D3 savvy users but will make the charts more complicated for more basic users.

Regarding the use cases you mention, for the first one, we are planning to add a 'chart annotations' [feature](https://github.com/eventbrite/britecharts/issues/473
). This will allow creating that line you mention.

In the second case, we are usually exposing some basic offset functions, assuming that many other transformations could be done via CSS overrides. I guess this would be the case?

What we can do now is to create an 'enhancement' proposal to expose the scales as public and see how much support that idea would have in the community. In the meanwhile, if you really need this, I would recommend you to fork the library and expose those yourself. It should be a really basic change where needed.

Thanks a lot for using Britecharts and for taking the time helping to improve the library with your feedback!
