### ISSUE TITLE
Bar chart - currency symbol

### ISSUE THREAD

**Issue by mnori** [britecharts/britecharts#641]
In my project it is important that a £ currency symbol is displayed in front of certain numbers. I can use something like this to get some formatting with the dollar sign, but I need it to be a pound (£) sign:

```
barChart
    .numberFormat("($.2f")
    .labelsNumberFormat("($.2f")
```
Changing "$" to "£" in the format string causes all the numbers on the chart to disappear.

I also tried using d3.formatDefaultLocale to change d3's currency symbol like this, but it also didn't work (maybe I did it wrong?)

```
d3.formatDefaultLocale({
	"decimal": ".",
	"thousands": ",",
	"grouping": [3],
	"currency": ["£", ""],
	"dateTime": "%a %b %e %X %Y",
	"date": "%d/%m/%Y",
	"time": "%H:%M:%S",
	"periods": ["AM", "PM"],
	"days": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
	"shortDays": ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
	"months": ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
	"shortMonths": ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
});
```

It may well be that I've overlooked some feature of d3 that would give me my £ sign.

## Expected Behavior
It would be nice if there was a way to specify the currency symbol.

## Current Behavior
Currency symbol restricted to $, afaik.

## Update:
I solved it for my project by simply replacing this line in the .min.js
`currency: ["$", ""]`
With this:
`currency: ["£", ""]`

This is obviously a yucky solution, but fine for my needs.

**Comment by Golodhros** [comment]
Hi @mnori, thanks for creating this issue!

Could you set up a codepen with your code so that we can debug it?

Thanks!

**Comment by Golodhros** [comment]
This shoudd be fixed with the new configurable locale object.
