### ISSUE TITLE
brush chart / line chart demo error in IE / Edge

### ISSUE THREAD

**Issue by flacoman91** [britecharts/britecharts#654]
## Expected Behavior
When selecting a range in the brush chart on the demo for the line chart, the line chart should update with the filtered data.

## Current Behavior
there is a data error after selecting date range, and the line chart goes away.

<img width="625" alt="screen shot 2018-08-08 at 9 51 00 am" src="https://user-images.githubusercontent.com/1038306/43842193-ca937866-9af2-11e8-8260-e219f2496b09.png">

## Steps to Reproduce (for bugs)

1. Using internet explorer 11, or MS Edge go to https://eventbrite.github.io/britecharts/tutorial-line.html
2. Select a date range and see the error occurring.
3.
4.

## Context

I'm testing the demo site in IE and found the error. 

## Your Environment

* Version used: 2.9.3
* Browser Name and version: Internet Explorer 11, MS Edge
* Operating System and version: Windows 7/10 virtual machine
* Link to your project or codepen:

**Comment by Golodhros** [comment]
Hi @flacoman91, thanks for opening this issue!

Definitely, a bug we should fix. Thanks for catching this one!

**Comment by Golodhros** [comment]
We'll probably just drop the IE support all over.
