### ISSUE TITLE
Increase Stacked Area number of areas limit

### ISSUE THREAD

**Issue by flacoman91** [britecharts/britecharts#663]
## Expected Behavior
the stacked area chart should be able to correctly handle any amount of data sources.

## Current Behavior
currently the stacked area chart's maxAreaNumber parameter is hard coded to 8.

https://github.com/eventbrite/britecharts/blob/master/src/charts/stacked-area.js#L140
The chart does not draw correctly when there are more than 7 data sources.

## Possible Solution
I suggest setting maxAreaNumber dynamically here
https://github.com/eventbrite/britecharts/blob/master/src/charts/stacked-area.js#L215
```

dataByDate = getDataByDate(data);
maxAreaNumber = dataByDate[0].values.length;

```
## Steps to Reproduce (for bugs)
1.  add a data source with more than 6 sources
2. the chart is now drawn incorrectly (see screenshot)
3.
4.

## Screenshots (if appropriate):
<img width="773" alt="screen shot 2018-09-24 at 12 18 20 pm" src="https://user-images.githubusercontent.com/1038306/45964513-0022b480-bff4-11e8-87a9-8cb4bac09875.png">

## Context
adding more rows breaks the chart rendering.

## Your Environment
* Version used:
* Browser Name and version:
* Operating System and version:
* Link to your project or codepen:

**Comment by Golodhros** [comment]
Hi @flacoman91, thanks for the issue!

This was limited by design. We think that having more than 7 areas would hurt readability of the chart and probably make the tooltip too bulky. We recommend to do some kind of grouping of the data beforehand, so it doesn't surpass that number of areas.

That said if you feel strongly against this decision we could create an enhancement proposal and see what other people think!

**Comment by flacoman91** [comment]
Thanks for the info.

Hi, I would like to make it an enhancement proposal.
We're using up to 10 areas in our charts and also floating the tooltip outside of the svg.

Ideally, I would like to have the chart be able to handle as many areas without breaking the scaling.

**Comment by Golodhros** [comment]
I see, would you be OK with limiting to 10 then?

**Comment by flacoman91** [comment]
having it limited to 10 would work for us.   Thanks!

Here's a screenshot of a sample chart we have.  
<img width="909" alt="screen shot 2018-09-27 at 9 24 05 am" src="https://user-images.githubusercontent.com/1038306/46148981-4451c700-c237-11e8-8d98-b92aba803e95.png">

**Comment by Golodhros** [comment]
Looks like done.
