### ISSUE TITLE
Add support for customising padding to the grouped bar chart

### ISSUE THREAD

**Issue by grayt0r** [britecharts/britecharts#674]
Add support for customising padding to the grouped bar chart, similar to the bar and stacked bar charts.

## Expected Behavior
Ability to customise the padding between bars/groups.

## Current Behavior
The padding is hardcoded to `0.1`.

## Possible Solution
Due to the nature of the grouped bar chart, simply porting the `betweenBarsPadding` functionality across might not be enough as it'd be useful to have different padding between bars within groups and between groups themselves - potentially adding `betweenBarsPadding` and `betweenGroupsPadding` options might work?

## Context
I'd like to keep a tight grouping of bars within a group, but have more whitespace between the groups to make it obvious they're separate.

## Your Environment
* Version used: 2.9.7
* Browser Name and version: Chrome 69
* Operating System and version: macOS High Sierra
* Link to your project or codepen: n/a

**Comment by grayt0r** [comment]
I'm more than happy to raise a PR to implement this change - just wanted to make sure it would be useful first.

**Comment by Golodhros** [comment]
Hi @grayt0r, thanks for opening the issue!

What you suggest makes a lot of sense, both paddings would be great!

Thanks a lot!!

**Comment by Golodhros** [comment]
Fixed by @ImADrafter, thanks!!
