### ISSUE TITLE
New Chart: Timeline Chart

### ISSUE THREAD

**Issue by rickardliljeberg** [britecharts/britecharts#676]
Plottable has an amazing chart with an even more amazing timeline axis. I would love it if britecharts would implement such a chart/timeline.

Here is the example:
http://plottablejs.org/examples/spacerace/

**Comment by Golodhros** [comment]
Hi @rickardliljeberg, thanks for creating this proposal!

A timeline could be a great chart to have. I have some other references as well:
- https://graves.cl/timeknots/example/index.html
- https://tympanus.net/Tutorials/InteractiveSVG/
- https://tympanus.net/Blueprints/VerticalTimeline/

Would love to see more examples!

**Comment by DalerAsrorov** [comment]
Nice! If I have spare time would love to work on it

**Comment by rickardliljeberg** [comment]
Personally what I want is like the spacerace link I sent but I would like to have the different colored dots on different rows and then have many rows. Plus a tooltip when hovering over a dot.

This way I intend to show activity of a user in multiple courses where each dot is an activity in a certain course (so one course per row on y-axis)

But what I love the most is their excellent time-axis which is much nicer than d3s built in!
