### ISSUE TITLE
Cannot get tooltip after resize

### ISSUE THREAD

**Issue by rickardliljeberg** [britecharts/britecharts#680]
I have a simple example of a stacked area chart. Everything works great on pageload with graph + tooltip.

However after I resize and I redraw the graph the tooltip no longer shows up. Codepen here: https://codepen.io/anon/pen/oaJLQr

-----------------------------------

I also noticed that I can get an error from start by simply having this code

```
container.datum(dataSet).call(stackedAreaChart);
			

chartTooltip
	.topicLabel('values')
	.title('Testing tooltip')

tooltipContainer = d3.select('#course-completions-stacked-chart .metadata-group .vertical-marker-container');
tooltipContainer.datum(dataSet).call(chartTooltip);

//This line causes the issues.
//Of course this is not needed in this code, but only here to simulate the problem from "on resize"
container.datum(dataSet).call(stackedAreaChart); 
```

So when I redraw the graph last like this my browser reports this on mousemove
![image](https://user-images.githubusercontent.com/3726818/47500305-c1865100-d862-11e8-9975-811dc94602b1.png)

**Comment by Golodhros** [comment]
Hi @rickardliljeberg, thanks for opening this issue!

About the resize, it seems you need to recreate the tooltip with each resize. I am not sure if this is expected, I will try to figure it out. Here is a codepen of this working: https://codepen.io/anon/pen/oaJLQr

Regarding your error, it kind of makes sense, as you are selecting the tooltipContainer before rendering the chart, so the container ('.metadata-group') is not there yet. The solution would be to first create, configure and RENDER the chart, then you can do all the tooltip related code.

**Comment by rickardliljeberg** [comment]
Hi!

Thanks you very much.
The codepen url seems to be the one I posted and not an updated one.

I still can't get it to work (trying to recreate tooltip). So would love the code showing this!

**Comment by Golodhros** [comment]
I see, sorry!

The content of the render function should be:

```
function resize(event) {

				var newContainerWidth = container.node() ? container.node().getBoundingClientRect().width : false;
        chartTooltip = britecharts.tooltip();
        chartTooltip
				  .topicLabel('values')
				  .title('Testing tooltip')
        
				// Setting the new width on the chart
				stackedAreaChart
          .width(newContainerWidth)
          .isAnimated(false)
          .on('customMouseOver', chartTooltip.show)
	  			.on('customMouseMove', chartTooltip.update)
	  			.on('customMouseOut', chartTooltip.hide);

				//Render the chart again
				container.datum(dataSet).call(stackedAreaChart);

        tooltipContainer = d3.select('#course-completions-stacked-chart .metadata-group .vertical-marker-container');
				        tooltipContainer.datum(dataSet).call(chartTooltip);

			}

```
