### ISSUE TITLE
Animate transitions between donuts chart ratios, rather than re-rendering from scratch

### ISSUE THREAD

**Issue by alexlenail** [britecharts/britecharts#687]
Say your data changes -- is there a way to animate a transition in a britechart (e.g. donut) or do you need to remove the chart and create a new one? 

```
var data = [{name: 'virginica', quantity: 100}, {name: 'setosa', quantity: 50}, {name: 'iris', quantity: 30}]

var donut = new Donut()
selection.datum(data).call(donut)

data = [{name: 'virginica', quantity: 100}, {name: 'setosa', quantity: 80}, {name: 'iris', quantity: 35}]

selection.datum(data).call(donut)

```

If it's possible to animate a transition, this issue is just a request for additional documentation on the subject.

**Comment by Golodhros** [comment]
Hi @zfrenchee, thanks for opening this issue!

Yes, you can update the data in your chart by doing:
```
  container.datum(newData).call(chart);

**Comment by zfrenchee** [comment]
@Golodhros when I pass new data via `.datum()`, the entire chart re-renders, with new colors. 

I'm hoping for behavior like [c3's donut](https://c3js.org/samples/chart_donut.html) where entering, exiting, and updating members of the donut smoothly animate transitions. 

Am I using it wrong, or is this intended behavior from Britecharts?

**Comment by zfrenchee** [comment]
@Golodhros see this fiddle: https://jsfiddle.net/k9hLn0x3/3/

**Comment by Golodhros** [comment]
Hi @zfrenchee, thanks for following up!

We don't support this feature as you mention. 

We could transform this into a feature proposal though.

Thanks!

**Comment by zfrenchee** [comment]
@Golodhros have been looking more into this, see:

- http://bl.ocks.org/mbostock/5100636
- https://bl.ocks.org/mbostock/4341417
- https://bl.ocks.org/mbostock/1346410
- https://bl.ocks.org/mbostock/5682158
- https://swizec.com/blog/silky-smooth-piechart-transitions-react-d3js/swizec/8258

**Comment by zfrenchee** [comment]
@Golodhros may make sense to change the `docs` label to a `proposal`, since this issue has changed -- I was originally looking for documentation on how to do this, but since it isn't built into britecharts, there's nothing to document, only something to build.

**Comment by Golodhros** [comment]
Hi @zfrenchee,

I see, makes sense! Thanks!
