### ISSUE TITLE
Clear off all tooltip remnants

### ISSUE THREAD

**Issue by rickardliljeberg** [britecharts/britecharts#690]
I settled on a graph where I show tooltips when it's over a certain threshhold and not when it's below.
There is a library to handle thresholds so I cannot use tooltipThreshold.

Instead I want to myself remove it on resize which I have working for the actual popup, however no matter what I do I still get the vertical lines and circles. Like this
![image](https://user-images.githubusercontent.com/3726818/47920552-9929d280-deb2-11e8-8357-62f4961a123c.png)

How can I clear those away when I no longer want tooltips?
I have also tested setting the tooltipThreshold on resize, like this

```
stackedAreaChart
					.width(newContainerWidth)
					.isAnimated(false)
					.tooltipThreshold(smallLayout ? 100000 : 0) 
```

But that seems to be ignores as far as the vertical line and circles are concerned because they still show up.

**Comment by Golodhros** [comment]
Hi @rickardliljeberg, thanks for the issue!

Oh, yeah, this is an old issue of us. Let me transform this into a bug.

Thanks!

In the meanwhile, I would remove this via a CSS override.

**Comment by Golodhros** [comment]
Setting tooltipThreshold as a high number seems to do the trick now.
