### ISSUE TITLE
Support Logarithmic scale axis

### ISSUE THREAD

**Issue by kanchev** [britecharts/britecharts#696]
Does britecharts support log scale for axis? I found out that it's possible to set the ticks but I actually need the distance between the ticks to be based on log with base 2, e.g. d3.scale.log().base(2).

**Comment by Golodhros** [comment]
Hi @kanchev, thanks for the question!

No, at this moment we don't support changing scales. It could be something we support going forward if enough people need it.

Out of curiosity, what is your use case?

**Comment by fsbraun** [comment]
Any time line plot of exponential growth would be a use case. Classic: **time lines of finance data.** I'd very much appreciate it, too!

**Comment by Golodhros** [comment]
We have this available on the Line chart and Stacked area chart.

Will close this for now, until somebody requests them for other charts.
