### ISSUE TITLE
Brite Chart: Date formate on X-axis labels is inconsistent for bar graph

### ISSUE THREAD

**Issue by florenceRency** [britecharts/britecharts#732]
Have to display month and date format in BRITE CHARTS for bar graphs (attaching the screenshot taking an example for line graph(used brite charts to display) )

Tried to display the month and date format in X-axis. But the values are overlapping each other

## Expected Behavior
Expected behavior: (NEED THE SAME DATE FORMAT TO BE DISPLAYED for bar chart too )
## Current Behavior
Current behavior: (values in the X-axis are over-lapping one-other)

## Screenshots (if appropriate)

<img width="927" alt="Screen Shot 2019-05-31 at 10 55 57 AM" src="https://user-images.githubusercontent.com/51215278/58813529-9084b080-85e9-11e9-87ee-9a8fcf6affc9.png">
<img width="992" alt="Screen Shot 2019-05-31 at 11 49 14 AM" src="https://user-images.githubusercontent.com/51215278/58813530-9084b080-85e9-11e9-8833-f1d25e281671.png">

**Comment by Golodhros** [comment]
Hi @florenceRency, thanks for opening this issue!

I understand you need to create a time series bar chart. We definitely don't cover that use case in Britecharts at the moment. Also, bar charts have a limitation when dealing with X-axis labels, as there is usually little room down there. 

One workaround we usually suggest is to make it a horizontal bar chart. I understand from your screenshot that this won't work for your use case.

Another workaround would be to rotate those labels, if you add this:
```
<style>
.tick text {
  transform: rotate(-45deg);
}
</style>
```
You would probably need to play around with the margins to make it look good.

Hope this works!

**Comment by Golodhros** [comment]
Did this work for you @florenceRency?
