### ISSUE TITLE
Dependencies are lying, as they are actually bundled

### ISSUE THREAD

**Issue by stof** [britecharts/britecharts#746]
The package.json lists d3, lodash.assign and base-64 as dependencies of the package. So npm will install them when using britecharts.
But these are not actually used at runtime. The `main` script points to the `dist/bundled/britecharts.min.js` file, which bundles these dependencies.

This has several drawbacks:

- if the project also uses d3 for other reasons, this will load it twice instead of sharing it
- if d3 makes some bug fixes, they won't be usable until britecharts makes a new release including them in its bundled version
- if there is a security issue in d3, there will be one in britecharts too for bundled versions including it. And due to the lack of reproducible build (as there is no lock file, the bundled version will change over time for the same source code), there is no way to track it.

The dependencies should be marked as external packages in webpack.

**Comment by Golodhros** [comment]
Hi @stof, thanks for opening this issue!

That's right, our bad. We are working currently into moving Britecharts into ES modules and we will tackle this as part of the project.

We plan to stop bundling D3.js along with Britecharts, although I think we'll keep the assign and base-64 as dev dependencies.

Thanks!

**Comment by stof** [comment]
@Golodhros that's fine to me if they are actually declared as dev dependencies. But that will still suffer from the same drawbacks. What about providing the best of both world ? You could have the `main` and `module` entrypoints pointing to files not bundling deps (as anyone relying on them would be using a bundler tool able to load the dependency) and then provide a separate bundle file bundling them, for people wanting to load the library without using a tool like webpack or rollup?

Btw, for d3, you should declare dependencies for the component packages, as that's what you actually require. Depending on the whole d3 package and requiring its transitive deps won't work without the npm/yarn hoisting algorithm (for instance when using yarn PnP mode)

**Comment by Golodhros** [comment]
Yep, that's the plan, also allowing tree shaking.

I see, you mean that we should add as dependencies the list of the different D3.js modules we use instead of the whole D3.js library?

**Comment by stof** [comment]
Yes, that's the solution to be compatible with yarn PnP, which does not give access to transitive deps through hoisting as it precisely does not use hoisting like npm.
Note that this will also avoid downloading all unused ones in projects as a benefit.



> Yep, that's the plan, also allowing tree shaking.

Then `lodash.assign` and `base-64` will not become dev dependencies.

**Comment by Golodhros** [comment]
Done in #908
