### ISSUE TITLE
Feature Proposal: labels on stacked bar chart

### ISSUE THREAD

**Issue by orangewit3** [britecharts/britecharts#747]
Enable labels for stacked bar chart

I wanted to know if the stacked bar chart could have a total count value at the end of the bars similar to the single bar chart component.

![Screen Shot 2019-07-17 at 12 19 35 PM](https://user-images.githubusercontent.com/43012690/61406766-5cabd480-a891-11e9-8397-234864e94a8c.png)
---------------------------
![Screen Shot 2019-07-17 at 12 24 01 PM](https://user-images.githubusercontent.com/43012690/61406773-60d7f200-a891-11e9-832d-5a436a8b14e4.png)

Essentially the API should have an enableLabels for stacked bar charts too because it is a very important feature as it saves space and allows for a more readable and clean UI.

The data I want to display is formatted like [someAttribute] : [subAttribute1 : COUNT] [subAttribute2 : COUNT] and a stacked bar chart is the most appropriate display. However, I want to have a label at the end of the bars that displays the total count to make it more readable along with other tool tips that display information on the sub attributes.

**Comment by Golodhros** [comment]
Thanks!
It makes sense, we should do it!

**Comment by DalerAsrorov** [comment]
I could implement that but I am not exactly sure how it should look like. @orangewit3 could you provide more details? Should it be on the top of each stacked bar?

**Comment by Golodhros** [comment]
won't do this for now.
