### ISSUE TITLE
Heatmap Chart Tooltip

### ISSUE THREAD

**Issue by Tsatia** [britecharts/britecharts#751]
Hi, 
it would be nice to also have a tooltip for the heatmap.
Something like this.

![Screenshot (7)](https://user-images.githubusercontent.com/27213628/62452680-f9ff7780-b770-11e9-96dc-bab27fdcd767.png)

**Comment by Golodhros** [comment]
Hi @Tsatia, thanks for this feature request!

It makes a lot of sense, I will add it as a feature proposal.

Thanks for using Britecharts!

**Comment by Golodhros** [comment]
Already implemented!
