### ISSUE TITLE
incorrect display big numbers

### ISSUE THREAD

**Issue by Tonypz** [britecharts/britecharts#757]
![image](https://user-images.githubusercontent.com/23166800/64168031-5975a380-ce53-11e9-9d46-7b3d113c1d94.png)

**Comment by Golodhros** [comment]
Hi @Tonypz, thanks for creating this issue!

What is it exactly that is wrong?
Do you know you can change the formatting by using "numberFormat" on the bar chart? http://eventbrite.github.io/britecharts/module-Bar.html#.numberFormat__anchor

**Comment by Tonypz** [comment]
Thank you, I didn’t know. Today I will try.
