### ISSUE TITLE
Lengthy names are breaking the Donut Chart and the legend 

### ISSUE THREAD

**Issue by karthikdivi** [britecharts/britecharts#760]
When the name is lengthy It's breaking both Donut Chart and the Legend 

![](https://res.cloudinary.com/karthikdivi/image/upload/v1568109937/temp/Screenshot_2019-09-10_at_3.32.57_PM.png) 

Here is the codepen to replicate https://codepen.io/karthikdivi/pen/oNvqoYV?editors=1010
What are the ways to handle these situations properly?

**Comment by Golodhros** [comment]
Hi @karthikdivi, thanks for opening this issue!

That's definitely a less than ideal experience. What do you think would be an better one?

I guess we could use the text wrapper with ellipses for both, would that work?

**Comment by karthikdivi** [comment]
Yes, @Golodhros wrapping helps up to some extent, at least it will stop the Donut Chart to break. And maybe if we can push the name to a hover text with full-line, that will help for long names.

**Comment by Golodhros** [comment]
I guess we could do that:
- calculate the width and height of the donut center and wrap the text within it
- allow to deactivate that center legend to use a mini-tooltip there

**Comment by Golodhros** [comment]
> > > The text inside can be truncated with an ellipses, like this. ![Donut_chart_1](https://user-images.githubusercontent.com/10022651/137170809-76b2f3d4-2ef5-4875-9009-3d21c8c28e0b.png)
> > 
> > 
> > Yeah, we have helpers for this kind of stuff in
> > https://github.com/britecharts/britecharts/blob/63ac07bf6f33fe9cbc0610c9f4a6dcabd3eb3ef6/src/charts/helpers/text.js#L89
> > 
> > This helper does not seem to have a font size, is that by choice?
> > > However, how can the full text be shown as a hover tool tip when the ellipsis is introduced? or as a configuration that would allow tool tip? It would make sense to have tool tip similar to how you have on the other charts. ![Hor_Bar_Chart](https://user-images.githubusercontent.com/10022651/137171395-9f7f4e76-c5bd-4007-bde5-f1df85de5733.png)
> > 
> > 
> > Yes, in theory, we should be able to plug the mini-tooltip now, using the 'customMouseOver', 'customMouseMove', and 'customMouseOut' events. I haven't tried it yet though.
> > The other missing part would be to add a configuration, maybe a 'hasCenterLegend' that defaults to true and that if set to false, would avoid writing in the center of the Donut.
> 
> I could try to setup a new configuration like you mentioned.

Awesome, thanks!

**Comment by Golodhros** [comment]
We can now avoid showing the legend, as contributed on https://github.com/britecharts/britecharts/pull/965
