### ISSUE TITLE
Bar chart to show percentage?

### ISSUE THREAD

**Issue by adamgruber** [britecharts/britecharts#761]
I'm trying to figure out if its possible to render a bar chart where the yAxis values are `0, 25%, 50%, 75%, and 100%` and the data is something like this:
```
[
  { name: 'a', value: 8 },
  { name: 'b', value: 10 },
  { name: 'c', value: 21 },
  { name: 'd', value: 47 },
  { name: 'e', value: 14 },
]
```

What I'm seeing now is this:
![image](https://user-images.githubusercontent.com/2378900/64988546-ac127f00-d899-11e9-95e9-300453ae63b6.png)

What I'm trying to do (ignore the tooltip):
![image](https://user-images.githubusercontent.com/2378900/64988578-bfbde580-d899-11e9-8a38-851617b9bb36.png)

**Comment by Golodhros** [comment]
Hi @adamgruber, thanks for the issue!

Have you tried setting .hasPercentage(true)?

Also, if you can provide a Codepen example I will be able to help you better!

**Comment by adamgruber** [comment]
@Golodhros I made a sandbox and messed around with it. Using the `percentageAxisToMaxRatio` option I can force the chart to always show 100% as the max value. However, I still am unable to configure the yAxis to show ticks for `0, 25%, 50%, 75%, 100%`

https://codesandbox.io/s/async-snow-73mw7

**Comment by Golodhros** [comment]
Ahh, the ticks issue!
Ticks in D3.js are something magic, we can try to influence them, but we don't have full control over them. If you set 3 ticks you would get 0, 50% and 100%, but I think that's as close as you can get.

I am sorry, there is no solution for this!
