### ISSUE TITLE
Britechart ignores d3.formatDefaultLocale

### ISSUE THREAD

**Issue by maikdiepenbroek** [britecharts/britecharts#773]
It seems that britecharts completely ignores any locale that is passed in.

## Expected Behavior
When d3.formatDefaultLocale() is called, i would expect any calls to d3.format to be in that specified locale.

## Current Behavior
Calling d3.formatDefaultLocale() with the desired locale does not work.

## Possible Solution
Maybe we could create a parameter to provide the chart builder with a custom locale, we could check if the parameter is present and then change the default locale.

## Steps to Reproduce
1. Create a new chart
2. Set the desired locale other than the default of 'en_US'
3. See the locale not change.

## Context
I'm using britecharts in my project to display graphs in a pdf generator. Since the user is passing a locale, and the numbers displayed are locale dependent (lots of currency related number) the formatting is really important for the integrity of the data.

## Your Environment
* Britecharts version used: 2.10.0
* Browser Name and version: Chrome 78

**Comment by maikdiepenbroek** [comment]
I got it to work by adding a new customLocale property, but since we need to pass that a complete locale object the api isn't that elegant. It's not really a possibility to let the user provide a simple locale 'nl_NL' and with that have the proper object fetched from an external source f.e.:
Right now:
`chart
  .width(400)	
	.customLocale({
    "decimal": ",",
    "thousands": ".",
    "grouping": [
      3
    ],
    "currency": [
      "€ ",
      ""
    ]
  })	
	.enableLabels(true)	
	.labelsNumberFormat('$,.2f')	
	.height(300)
`

Preferred:
`chart
  .width(400)	
	.customLocale('nl_NL')	
	.enableLabels(true)	
	.labelsNumberFormat('$,.2f')	
	.height(300)`

**Comment by Golodhros** [comment]
Hi @maikdiepenbroek, thanks for following up with all this!

I am aware of this issue but I am not sure about the right solution. It seems it should take some extra time to analyze properly. When we created Britecharts, we didn't know about 'formatDefaultLocale' (if it actually existed back then), and now we have a good amount of formatting functions all over the library.

As I see it now, I think we have some options:
1. We add the 'customLocale' option you suggest to all our charts. Internally, that would go into a helper that would load the locale and set it asynchronously.
1. We actually get rid of all our formatting functions and delegate to d3-format to do all the localization via d3.formatDefaultLocale.

My favorite option right now is the second, as it would allow us to reduce our interface greatly, simplifying the library maintenance. However, maybe users would not like it that much, and we should definitely educate them with tutorials about how to do localization with Britecharts.

It seems that both options would require breaking changes, so they would go into Britecharts 3.0, do I don't think I have a quick fix for you here.

What do you think @DalerAsrorov?

**Comment by maikdiepenbroek** [comment]
@Golodhros Thanks for the extensive and honest answer!  

I would like option 2 as well since you indeed delegate the formatting work to the d3-format library which can do it for you. Just so i understand it correctly, is it true that britecharts has custom formatting functions that are independent on d3-format ? 

If that's the case i could make some suggestions through a PR which removes the custom formatters and replaces them with d3-format ones. Next to that we should also make it possible to override the default locale via a parameter. Once we're settled on the solution we can finish implementing it and then (re)write some docs to help users transition into 3.0. 

Does that sound like a plan ? @DalerAsrorov and @Golodhros ?
Ps. Great work on the developer experience, i got up to speed with a local version of britecharts in no time! 👍

**Comment by maikdiepenbroek** [comment]
I've worked on a different approach, exposing a defaultLocale on top level f.e.:

```
const chart = britecharts.defaultLocale('nl-NL');
chart.bar(); 
```
When called with a string, it fetches the correct locale format from `https://cdn.jsdelivr.net/npm/d3-format/locale/nl-NL.json` which is a constant. in `/helpers/constants`
The defaultLocale also accepts an object in the form of:
```
{
  "decimal": ",",
  "thousands": ".",
  "grouping": [
    3
  ],
  "currency": [
    "€ ",
    ""
  ]
}
```

In this way, the britecharts library can remain the same since a lot of formatting functions already use the `d3-format` library.

**Comment by maikdiepenbroek** [comment]
> I've worked on a different approach, exposing a defaultLocale on top level f.e.:
> 
> ```
> const chart = britecharts.defaultLocale('nl-NL');
> chart.bar(); 
> ```
> 
> When called with a string, it fetches the correct locale format from `https://cdn.jsdelivr.net/npm/d3-format/locale/nl-NL.json` which is a constant. in `/helpers/constants`
> The defaultLocale also accepts an object, which sets the config directly without making a xhr call, this object is in the form of:
> 
> ```
> {
>   "decimal": ",",
>   "thousands": ".",
>   "grouping": [
>     3
>   ],
>   "currency": [
>     "€ ",
>     ""
>   ]
> }
> ```
> 
> In this way, the britecharts library can remain the same for the most part since a lot of formatting functions already use the `d3-format` library.

Seems like this approach isn't going to work. Since the defaultLocale call on top level does not return the britecharts instance  for the subsequent calls. Not quite sure what the proper solution is, any help or tips are more than welcome!

**Comment by Golodhros** [comment]
Hi @maikdiepenbroek, thanks for digging on this!

We don't have custom formatters AFAIK, we always use d3-format, so I really don't know why it is not working. That's another reason why this issue seems to need a deeper evaluation on the Britecharts side.

Glad to hear your development experience was good! We really think this is important in order to get more help from contributors. Did you use the docker container?

Your approach using the top-level Britecharts object looks good, but it won't work as a general solution as we allow users to load individual charts, so the top object is not always present.

If you have time to work on this, I would suggest you grab the simplest britechart chart that has formatters like the step chart and try to figure out why the defaultLocale doesn't work. Once we know that, we'll be able to think in a solution that works for all charts, or just to fix whatever it is overriding it.

Thanks a lot!

**Comment by maikdiepenbroek** [comment]
> We don't have custom formatters AFAIK, we always use d3-format, so I really don't know why it is not working. That's another reason why this issue seems to need a deeper evaluation on the Britecharts side.

Oh, i thought you mentioned that as a solution, moving all the formatters to use d3-format, but this is already the case then..

> Glad to hear your development experience was good! We really think this is important in order to get more help from contributors. Did you use the docker container?

I did not, just cloned the repo and followed the steps :)

>If you have time to work on this, I would suggest you grab the simplest britechart chart that has formatters like the step chart and try to figure out why the defaultLocale doesn't work. Once we know that, we'll be able to think in a solution that works for all charts, or just to fix whatever it is overriding it.

Cool, i'll fiddle around some more until i get a better feeling of what is going wrong! I'll keep you updated.

**Comment by maikdiepenbroek** [comment]
I have a PR open with a work in progress of a possible solution: https://github.com/eventbrite/britecharts/pull/777/files

If this seems like a good idea, i could implement it in all the charts and alter docs/tests etc. 

Please let me know what you think!

**Comment by Golodhros** [comment]
Thanks a lot @maikdiepenbroek! Just commented on your PR

**Comment by Golodhros** [comment]
I think this is almost done, we need to add locale to:
- bullet chart
- donut chart
- heatmap
- mini tooltip
- scatter plot

The implementation should be the same as in the current charts, so it should be copy/paste mainly

**Comment by Golodhros** [comment]
It seems we have a conflict between this locale and the date locale.

We could do something like 'amountLocale' and 'dateLocale' to disambiguate.

**Comment by maikdiepenbroek** [comment]
@Golodhros Thanks for keeping this alive, although i'm still using a custom version of britecharts with the fix in it i never got around to actually finishing my PR. Sorry for that!

If we settle on the naming i could look at the existing implementation and add it to the remaining charts as well so we can finish this PR once and for all haha.

**Comment by Golodhros** [comment]
> @Golodhros Thanks for keeping this alive, although i'm still using a custom version of britecharts with the fix in it i never got around to actually finishing my PR. Sorry for that!

No prob @maikdiepenbroek, this happens a lot!

> If we settle on the naming i could look at the existing implementation and add it to the remaining charts as well so we can finish this PR once and for all haha.

That would be awesome! We are reading version 3 and we have a pile of work to do!
In my mind, the process would be something like:
1.- Rename all the current 'locale' options into 'dateLocale' and 'amountLocale'
2.- Extend the 'amountLocale' implementation on bar, groupedBar and scatterPlot to the rest of charts 
3.- Extend (if needed) the 'dateLocale' implementation to all time-based charts

Any help you could give us in this process would be really appreciated!
