### ISSUE TITLE
Add a mention on the Tooltip API docs to recommend a maximum of elements to show

### ISSUE THREAD

**Issue by Lennen** [britecharts/britecharts#788]
## Expected Behavior

The tooltip height should be enough as for 3 values in the tooltip list, so as for 20 values.

## Current Behavior

The tooltip height is decreasing during the increment of legend positions inside of the tooltip.

## Steps to Reproduce

1. Choose the grouping bar.
2. Use the attribute of the chart so as there will be more than 10 values inside of the tooltip. 
3. Draw the chart and make the tooltip visible.
4. See the ugly bottom of the tooltip without the beautiful padding.

## Screenshots (if appropriate)
https://ibb.co/sQs04wR

## Your Environment

* Britecharts version used:
* Browser Name and version:
* Operating System and version:
* Link to your project or codepen:

**Comment by Golodhros** [comment]
Hi @Lennen, thanks for opening the issue!

The link you provided doesn't work, could you update it?

**Comment by Lennen** [comment]
> Hi @Lennen, thanks for opening the issue!
> 
> The link you provided doesn't work, could you update it?

Ok, done it

**Comment by Golodhros** [comment]
Hi @Lennen, thanks for the link!

So, this is true, we don't recommend to include more than seven elements on a chart showing a Tooltip. It could work for 10 items as you have in the example, but still won't look good.

I would recommend you to maybe group some of the data sets, having six groups plus an aggregation called "other" or something similar.

It is true that we could give more explicit guiding in the API documentation of the Tooltip, so I will modify this ticket so we add it.

Thanks!

**Comment by Lennen** [comment]
Is it possible to add a scrollBar inside of the toolTip?

**Comment by Lennen** [comment]
> Hi @Lennen, thanks for the link!
> 
> So, this is true, we don't recommend to include more than seven elements on a chart showing a Tooltip. It could work for 10 items as you have in the example, but still won't look good.
> 
> I would recommend you to maybe group some of the data sets, having six groups plus an aggregation called "other" or something similar.
> 
> It is true that we could give more explicit guiding in the API documentation of the Tooltip, so I will modify this ticket so we add it.
> 
> Thanks!

Is it possible to add a scrollBar inside of the toolTip?

**Comment by Golodhros** [comment]
Hi @Lennen,
I think you could do that, yes. You would need to set a CSS override, search for the tooltip container and add overflow: scroll to it. It would probably work.

However, we don't want to add this feature to the library at this moment.

**Comment by Golodhros** [comment]
Addressed in 3.0.0 by #1051 (and #1049). The tooltip now keeps itself inside the chart, so a long list is never cut off, and a new `maxEntries` accessor (default 12, 0 for all) folds the rows past it into a "+n more" row. The API docs describe it.
