### ISSUE TITLE
A long name with an any long word inside of the Tooltip is displaced down relatively to its marker one the one string 

### ISSUE THREAD

**Issue by Lennen** [britecharts/britecharts#789]
## Expected Behavior

Text and its marker inside of the tooltip should be on the same line without any dependence on the text content. 

## Current Behavior

When there are long words inside of the names of the tooltip, the string goes down relatively to the its marker.

## Possible Solution

To split words inside of the tooltip or to create a parameter of max tooltip width.

## Steps to Reproduce

1. Make the chart with the tooltip.
2. Create any number of the values inside of the tooltip.
3. Make one note inside of the tooltip with a long word length.
4. See the displacement of the text with long word relatively to the its marker and color signature.

## Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/7087581/75526333-a2816b80-5a22-11ea-81a6-cb3e31d2820c.png)

## Your Environment

* Britecharts version used: 
* Browser Name and version: Google Chrome.
* Operating System and version:
* Link to your project or codepen:

**Comment by Golodhros** [comment]
Hi @Lennen, thanks for creating this issue!

I am curious, what is your use case?
We are currently supporting multi-line entries in the tooltip, but as you found out, a really long word breaks the UI.

One thing you could do is to find that element with CSS and apply overflow: hidden; However this would break the multi-line use case.

**Comment by Golodhros** [comment]
Closing this as a very edge case. Feel free to reopen.
