### ISSUE TITLE
Sample json data incorrect

### ISSUE THREAD

**Issue by flacoman91** [britecharts/britecharts#791]
In the following sample json file, https://github.com/eventbrite/britecharts/blob/master/test/json/lineDataOneSet.json

It appears that there's duplicate, or incorrect date keys in the data.

 ```
  {
                    "date": "2016-07-31T16:00:00-08:00",
                    "value": 0,
                    "date": "2016-07-31T00:00:00-07:00"
  ,
```

## Steps to Reproduce
1. Look at code here https://github.com/eventbrite/britecharts/blob/master/test/json/lineDataOneSet.json
2.
3.
4.

## Your Environment

* Britecharts version used:
* Browser Name and version:
* Operating System and version:
* Link to your project or codepen:

**Comment by Golodhros** [comment]
Hi @flacoman91, thanks for pointing this out!

Yeah, they only change the hour, we should probably clean it!

**Comment by Golodhros** [comment]
Fixed on https://github.com/britecharts/britecharts/pull/831
