### ISSUE TITLE
Stacked and Grouped Bar: Tooltip dissappears randomly

### ISSUE THREAD

**Issue by Lennen** [britecharts/britecharts#795]
## Expected Behavior
Tooltip should reveal everytime when I put mouse cursor on the rectangles of the Stacked Bar chart.

## Current Behavior

In many cases with cursor on the rectangle it works well, but I tried to make a click on the plot and after that to get Tooltip the same way. It doesn't worked. There also is used a widget to get and to set a properties for the plot when I make mouse clicks. 

But it seems the problem is not with a set incorrect parameters during that, but in the Tooltip.  Everytime I made a debug, all works fine, the tooltip appears well. But there was no highlight for the selected rectangle. The problem is, so, that without debugging some another function make role. During that, the tint of the rectangle is changed, but the tooltip is not appeared. Anyway, when I'm using another type of the chart, there is no the same problem, tooltip is appeared well anytime it should appear.

## Possible Solution

Maybe there are two conflicting options in the Stacked Bar.

## Steps to Reproduce

1. Use the Stacked Bar with Tooltip.js
2. Make a click on the any rectangle element on the Chart or make some function after you have rendered the Stacked Bar Chart. 
3. It can be possible that Stacked Bar will not appeared, you will see just the change of the rectangle color on the mouse over this object.

## Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/7087581/76433198-0dd52100-63c5-11ea-94ef-baf258b7f608.png)

![image](https://user-images.githubusercontent.com/7087581/76434582-eaab7100-63c6-11ea-85d0-e412006158d1.png)

## Your Environment

* Britecharts version used:
* Browser Name and version:
* Operating System and version:
* Link to your project or codepen:

**Comment by Golodhros** [comment]
Hi @Lennen, thanks for creating this bug report!

I have been playing around with the tooltip in the stacked bar chart and it is true there is some weirdness and cases where the tooltip dissapears.

It doesn't happen always, but if I hover a bar and see the tooltip, if I go over the tooltip itself with the mouse and move up and down on the bars, it dissapears.

**Comment by Golodhros** [comment]
This happens on the grouped bar chart too.
