### ISSUE TITLE
Displacement of the tooltip date relatively to x-axis date in the line charts 

### ISSUE THREAD

**Issue by Lennen** [britecharts/britecharts#796]
I have a dataset. When I try to render it using the Line Chart, all is ok with  dates on the x-axis. However, when I search for the date near the Tooltip name of the Tooltip, there is a date displacement (the 27 of August becomes to the 26 of August). 

## Expected Behavior

If I have a point on the Line Chart with a date 27 of August, on the Tooltip I should see the same date 27 of August.

## Current Behavior

In tooltip I can see 26 of August while the correct date is 27 of August for this point. For tooltip there is a delay on the one sample of date.

## Steps to Reproduce

1. Create Line chart.
2. See the displacement in the tooltip

## Context

Maybe it can be fixed using some special parameter or by the correction of the data format.

## Your Environment

* Britecharts version used:
* Browser Name and version:
* Operating System and version:
* Link to your project or codepen:

**Comment by Golodhros** [comment]
Hi @Lennen, thanks for opening this issue!

Could you set up a codepen to reproduce this issue? You could take this one as a jump start point: https://codepen.io/Britecharts/pen/yravbr

Thanks!

**Comment by Golodhros** [comment]
I think this could be a timezone issue, hard to debug without an example, so closing it for now.
