### ISSUE TITLE
2.14.4: NPM Package is broken

### ISSUE THREAD

**Issue by robertmclaws** [britecharts/britecharts#797]
The 2.14.4 release changed something in the publishing processs... the NPM package now only contains the GitHub source tree, and not the compiled outputs. I had to revert back to 2.13.2 in order to get my webpack build working again.

**Comment by Golodhros** [comment]
Hi @robertmclaws, thanks for raising this issue!

I will check it ASAP!

**Comment by Golodhros** [comment]
Hi @robertmclaws, check the new version 2.14.6, it should be back to work!!

Thanks!
