### ISSUE TITLE
Feature Proposal: Possibility to cut zeros after coma for NumberFormat

### ISSUE THREAD

**Issue by Lennen** [britecharts/britecharts#810]
On the page https://britecharts.github.io/britecharts/tutorial-step.html we can see that there are numbers on the Mini-tooltip "300.00", "250.00" etc, here can be also 5550.50 (so as on Tooltip). Why not "300", "250" and "5550"? This way, we can have a more space to place an integer part of the number.

## Expected Behavior

We have extra zeros after coma, which can be hidden and not displayed. We can change the numberFormat (.0f), but this way for the number 5550.50, for instance, there will be loss in information in the fractional number part.

## Difference from Current Behavior

We must see "250" instead of "250.00", but if there is also a number here like 5550.50, it should be written this way: "5550.5". 

## Example Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/7087581/80389776-37360780-88b4-11ea-8e9f-e7cf45c06d9b.png)

**Comment by Golodhros** [comment]
Yes, this is already available.
On the Mini-Tooltip API () you can use .numberFormat to set it to "". That way we'll remove the two zeros.
