### ISSUE TITLE
xTicks is not working for BarChart

### ISSUE THREAD

**Issue by Lennen** [britecharts/britecharts#813]
xTicks is not working for BarChart

## Expected Behavior

We should restrict xAxis labels using xTicks

## Current Behavior

The labels on the xAxis are not changing.

## Steps to Reproduce

1. To use xTicks while Chart plotting
2. To use also yTicks to be sure you did no errors
3. See that yTicks works while xTicks no.
4.

## Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/7087581/81209355-1b7be100-8fd9-11ea-94cd-3b6fb30bd38a.png)
![image](https://user-images.githubusercontent.com/7087581/81209643-7a415a80-8fd9-11ea-9f46-bd19de2bb4df.png)

## Your Environment

* Britecharts version used:
* Browser Name and version:
* Operating System and version:
* Link to your project or codepen:

**Comment by Golodhros** [comment]
Hi @Lennen, thanks for opening this issue!

Ticks are definitely tricky on D3.js, as they don't really "work" as requested, only on an approximate way. From what I see on your chart, there are a lot of entries, so probably an horizontal bar chart will probably work better.

Anyways, if you put it on a codepen I could try to find a good solution. (use https://codepen.io/Britecharts/pen/yEwpeg as a jumpstart)

**Comment by Golodhros** [comment]
Closing for now.
