### ISSUE TITLE
Width 100% bug 

### ISSUE THREAD

**Issue by Tonypz** [britecharts/britecharts#814]
Hi @Golodhros  !  
How to make the width of the chart 100% ?
Thank you !

**Comment by Golodhros** [comment]
Hi @Tonypz,

For now, you need to manually set the width of the chart to the size of its container and render it. If you check our demos, you can see how to make this responsive by listening to changes on the viewport width.

**Comment by Tonypz** [comment]
Ok,  @Golodhros. Also made. Thanks.
