### ISSUE TITLE
Change color for StepBar

### ISSUE THREAD

**Issue by Tonypz** [britecharts/britecharts#815]
@Golodhros  HI ! How to change color  for stepBaR ?  (https://codepen.io/Britecharts/pen/OxWQjN)
![image](https://user-images.githubusercontent.com/23166800/81279268-92f45380-905f-11ea-9b98-8c582ca112b7.png)

**Comment by Golodhros** [comment]
Hi @Tonypz,

It seems that chart doesn't have configurable colors. I really recommend you to not use that chart, as we are going to deprecate it.

If you still need to use it, I recommend you to change its colors via CSS, by setting the 'fill' property of the bars to whatever color you want.

**Comment by Tonypz** [comment]
ok, @Golodhros  what is the alternative solution ? use bar chart ?

**Comment by Golodhros** [comment]
Yeah, I would go with a bar chart for sure.
