### ISSUE TITLE
Change view data for tooltip 

### ISSUE THREAD

**Issue by Tonypz** [britecharts/britecharts#816]
Can I somehow add values ​​or replace with my tooltip ?
![image](https://user-images.githubusercontent.com/23166800/81289580-54669500-906f-11ea-976d-f9b2540b9183.png)

**Comment by Golodhros** [comment]
Hi @Tonypz,

Not sure if I understood right, do you want to render the large tooltip on a bar chart?

**Comment by Tonypz** [comment]
Yes @Golodhros , I want to have more information in the tooltip than on default

**Comment by Golodhros** [comment]
I am afraid is not possible for now.
We have plans to rework a bit the tooltip and merge both to give you more options, but for now each chart has only one Tooltip option.

**Comment by Tonypz** [comment]
ok ! thanks !
