### ISSUE TITLE
Only integer y-axis

### ISSUE THREAD

**Issue by Tonypz** [britecharts/britecharts#817]
Hi @Golodhros ! 

I have a question again. I have value = 1, I want only integer values ​​to be displayed along the Y-axis. 

![image](https://user-images.githubusercontent.com/23166800/81373069-85dd7000-9104-11ea-97cc-5f16c74a0c17.png)

**Comment by Golodhros** [comment]
Hi @Tonypz,

In D3.js, the amount of ticks is not completely controllable, but you can try some things.
Try first changing the format to a rounded format with '.numberFormat(".0")'.
Another thing you can try is to reduce the number of ticks with `.yTicks(2)`

Not sure if this is going to work though, it isn't something we can totally control.

**Comment by Lennen** [comment]
.numberFormat('.0') After this string the error appears:
![image](https://user-images.githubusercontent.com/7087581/81437267-90831e00-9173-11ea-8e3f-819256f35373.png)

**Comment by Golodhros** [comment]
Interesting, I got it working on the CodePen, I will try to check on the sandbox today.

**Comment by Lennen** [comment]
About the last my post - It was just syntax error, sorry. All is ok about .numberFormat('.0f') for barChart and .valueLabelFormat('.0f') for the StackedBarChart
