### ISSUE TITLE
Y-ticks property is not working correctly

### ISSUE THREAD

**Issue by Lennen** [britecharts/britecharts#820]
When I am trying to change the argument of the property .yTicks(argument);, I'm receiving an interesting result which is shown on the attached images for the Stacked Bar Chart case. It seams if tickNum < 5, the yTicks property is not working.

## Expected Behavior

If I'm putting .yTicks(3), there should be 3 points on the y-axis including the 0. 

## Current Behavior

I'm putting .yTicks(3), but on the y axes there are 5 values as for default.

## Steps to Reproduce

1. Use .yTicks(3) with a data represented on the pictures;
2. See 5 ticks on the plot.

## Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/7087581/83004269-1fb77f00-a018-11ea-8d2a-de3b64bf4c34.png)
See the highest plot from the tripled chart.

For 0 tiks:
![image](https://user-images.githubusercontent.com/7087581/83004693-a5d3c580-a018-11ea-9626-fcb60fc8d41d.png)
For 1 tick:
![image](https://user-images.githubusercontent.com/7087581/83004756-b97f2c00-a018-11ea-9420-c22b80aa076f.png)
For 2 ticks:
![image](https://user-images.githubusercontent.com/7087581/83004822-cac83880-a018-11ea-9be6-2d4b3af2d267.png)
For 3 ticks:
![image](https://user-images.githubusercontent.com/7087581/83004946-e7fd0700-a018-11ea-91b7-592c71cdc241.png)
For 4 ticks:
the same as for 3 ticks
For 10 ticks:
![image](https://user-images.githubusercontent.com/7087581/83005027-0105b800-a019-11ea-98a6-50d7d14c13fd.png)

## Your Environment

* Britecharts version used:
* Browser Name and version:
* Operating System and version:
* Link to your project or codepen:

**Comment by Golodhros** [comment]
Hi @Lennen, thanks for creating this issue!

Yeah, I am sorry, this is something a lot of people have asked about. Sadly, the level of control that D3.js offers on the ticks side is not complete. It kind of works, but only more or less, as you have experienced.

In summary, I am afraid there is nothing we can do for now. Maybe if D3.js change this in the future we will be able to support it.

Thanks!
