### ISSUE TITLE
Tooltip: Allow category keys as well as date and number for including in tooltip title

### ISSUE THREAD

**Issue by scottbw** [britecharts/britecharts#825]
## Expected Behavior
tooltip.xAxisValueType currently accepts one of "date" and "number". This should also accept "category". Where category is set, the tooltip.formatKey function should return the unmodified string.

## Difference from Current Behavior
Tooltip titles can only show dates or numbers. If the xAxis uses a category variable, you can either show nothing, or "NaN".

## Possible Implementation
See above, essentially a bypass of the formatKey() function. Note that mini-tooltip already seems to default to using an unmodified key in the title.

## Context
I'm using Britecharts in a BI context. I often need to show stacked bars using category dimensions.

**Comment by Golodhros** [comment]
Hi @scottbw, thanks for opening this ticket!

That sounds legit. I will make it a feature proposal. 
We still have pending a rework of our tooltips, this should be part of it!

**Comment by Golodhros** [comment]
Fixed in 3.0.0 by #1051. `xAxisValueType` gains `'category'`, which shows the key as it is, and `'auto'`, now the default: a date shows as a date, a number as a number, anything else as it is. A category key no longer titles the tooltip NaN. `'date'` and `'number'` still force a type.
