### ISSUE TITLE
Bar chart where all data = 0 shows bars

### ISSUE THREAD

**Issue by chinaowl** [britecharts/britecharts#827]
## Expected Behavior

I would not expect to see any bars, since everything is 0.

## Current Behavior

There are bars and the first y-tick is 0, but that should be the base of the chart:
![image](https://user-images.githubusercontent.com/2628718/88957582-e982bf80-d253-11ea-952f-839b1cff5164.png)

Note that as soon as I change one of the data points to be > 0, it looks correct:

![image](https://user-images.githubusercontent.com/2628718/88958239-08ce1c80-d255-11ea-8f60-2a36f2b1788a.png)

## Steps to Reproduce

I started with the pen linked [here](http://britecharts.github.io/britecharts/installing-britecharts.html) and changed all the data to 0 to repro the bug. See https://codepen.io/chinaowl/pen/ZEQdmwW.

## Screenshots (if appropriate)
See above.

## Context

I'm not sure but I think we started seeing this when we updated to 2.16.0 (but we were on a much older version before, 2.5.1).

## Your Environment

* Britecharts version used: 2.16.0
* Browser Name and version: Chrome 84
* Operating System and version: macOS Mojave
* Link to your project or codepen: https://codepen.io/chinaowl/pen/ZEQdmwW

**Comment by Golodhros** [comment]
Hi @chinaowl, thanks for opening this issue!

This is definitely a bug, and a really bad one! Unacceptable. 
I guess it has to do with the work we made to support negative values in our charts.

I will take a look at this during this week, in the meanwhile, could you try to load an older version of Britecharts to see if the problem goes? Would love to know as well which specific version starts working again!

Thanks,

**Comment by chinaowl** [comment]
@Golodhros I tried a few different versions and 2.13.2 works!

**Comment by Golodhros** [comment]
> 
> 
> @Golodhros I tried a few different versions and 2.13.2 works!

Awesome!
I am taking a look at it right now, it is odd as it only happens when all the values are 0.

**Comment by ajdani** [comment]
What would be the expected behaviour @Golodhros ?

**Comment by Golodhros** [comment]
We just released Britecharts 2.16.1 with a fix, please take a look @chinaowl!

Thanks to @ajdani for the fix!
