### ISSUE TITLE
`Latest` release on Github not showing the latest version

### ISSUE THREAD

**Issue by ajdani** [britecharts/britecharts#840]
Hi,

I just saw that the latest release on the Github page is pointing to a old version (2.3.0 from Oct 2017), I guess this should not be like that:
![image](https://user-images.githubusercontent.com/16606530/91563663-8b72f600-e93f-11ea-8b78-b4012a197d31.png)

Can be seen here:
https://github.com/britecharts/britecharts

I guess it's only needed for the next release to tag it as `latest` or something like that. Unfortunately I'm not that into Github now, that I know exactly what is needed to change the version there.

But I would suggest to update this bit of information, as it may be confusing and the project may seem unmaintained at the first sight for new potential users.

**Comment by Golodhros** [comment]
Interesting! Thanks for opening this issue @ajdani !

It seems Github only sees releases triggered from the Github UI itself, and we only did that once back then! 

I will do some research and see how to fix this. Thanks for raising it!

**Comment by Golodhros** [comment]
It seems that the new Github UI doesn't even show this anymore, so I will close this for now.
