### ISSUE TITLE
Add basic configurations to Heatmap

### ISSUE THREAD

**Issue by Golodhros** [britecharts/britecharts#845]
## Expected Behavior
We should have some extra basic accessors for the heatmap:
- locale
- loadingState
- isAnimated
- numberFormat?

## Difference from Current Behavior
The current API is so minimal is almost unusable

## Possible Implementation
Follow other chart's examples

**Comment by DalerAsrorov** [comment]
Currently working on this. `numberFormat` doesn't make sense for heatmap IMO

**Comment by DalerAsrorov** [comment]
Is there a tool that kind of helped you build the loading states or you wrote `svg` components from scratch somehow?

**Comment by Golodhros** [comment]
> Have a few questions:
> 
> * Is there a tool that kind of helped you build the loading states or you wrote `svg` components from scratch somehow?

They were sketch designs, downloaded as SVGs. The animations are the same, so we would need a rectangle for this one I guess.

> * How does `locale` get applied here? I have a bit hard time understanding of how the `locale` can be added by looking at the current examples. Charts like `stacked-area` and `bar` have axis and that's where the `locale` is primarily used. To build the scales and ticks.

Here the problem is that right now the heatmap is only of hours of a week, and it should be more flexible to do other timeframes that would need that localization. In our current case, once we plug the mini-tooltip, we could show the date for each square, and that might need locale info.

**Comment by Golodhros** [comment]
Loading state tracked here: https://github.com/britecharts/britecharts/issues/942
