### ISSUE TITLE
Grouped/stacked bar charts display bars when all values are 0

### ISSUE THREAD

**Issue by grayt0r** [britecharts/britecharts#846]
Appears to be the same as https://github.com/britecharts/britecharts/issues/827 but for grouped and stacked bar charts.

## Expected Behavior
If all values are 0 then no bars should be displayed.

## Current Behavior
Grouped:
<img width="518" alt="Screenshot 2020-09-10 at 10 22 28" src="https://user-images.githubusercontent.com/387478/92710312-966e5300-f34f-11ea-9c26-5b9fa208d77d.png">

Stacked:
<img width="941" alt="Screenshot 2020-09-10 at 10 22 39" src="https://user-images.githubusercontent.com/387478/92710341-9d956100-f34f-11ea-93c7-c317f415c447.png">

As soon as one of the values is greater than 0 the charts render correctly.

## Possible Solution
Possibly similar to the fix for the linked issue: https://github.com/britecharts/britecharts/pull/829.

## Steps to Reproduce
https://codepen.io/grayt0r/pen/ZEWxXxv

## Screenshots (if appropriate)
See above.

## Context
Currently this is just preventing us from upgrading the version of britecharts we're using.

## Your Environment
* Britecharts version used: 2.16.1
* Browser Name and version: Chrome 85
* Operating System and version: macOS Catalina
* Link to your project or codepen: https://codepen.io/grayt0r/pen/ZEWxXxv

**Comment by Golodhros** [comment]
Thanks for opening this issue @grayt0r !

Fix is on its way!

**Comment by grayt0r** [comment]
@Golodhros amazing, thank you! 🙌
