### ISSUE TITLE
Blank spaces for the 600+ samples inside of a limited chart width

### ISSUE THREAD

**Issue by Lennen** [britecharts/britecharts#847]
Hello, there is a problem when I'm using 623 samples inside of the chart. So while the width of the window is great, all is okey. But when I'm going to reduce the space, where the chart is drawn, there the blank spaces appear inside of the chart. How can I avoid that?
![image](https://user-images.githubusercontent.com/7087581/92762015-e1618800-f39a-11ea-8de9-7b478f2266f7.png)

**Comment by Golodhros** [comment]
Hi @Lennen, thanks for the issue!

Interesting, it looks like it is re-drawing the axis but not the bars.
Could you try to reproduce it on a Codepen like https://codepen.io/Britecharts/pen/yEwpeg ?

Thanks!

**Comment by Lennen** [comment]
![image](https://user-images.githubusercontent.com/7087581/92953029-a5e1bf00-f469-11ea-9828-3a89bb2cc4b1.png)
So here we are. Here you can see, if there are a lot of samples (200+) with a long names, the chart will be collapsed to the center, white the text is on the same place.

**Comment by Lennen** [comment]
But for my case it looks strager because of without any deleting of the information drawn on the X-axis we can see that all chart has been collapsed (bars so as x-axis labels)
![image](https://user-images.githubusercontent.com/7087581/92953818-0e7d6b80-f46b-11ea-81e7-ad3c889b8a72.png)

**Comment by Golodhros** [comment]
Could you send me the link of your Codepen so I can check it?

**Comment by Golodhros** [comment]
I tried here https://codepen.io/Britecharts/pen/yEwpeg?editors=1010 but couldn't reproduce this.
