### ISSUE TITLE
I want to know, where I'm clicked inside of the Stacked bar chart column

### ISSUE THREAD

**Issue by Lennen** [britecharts/britecharts#864]
## Expected Behavior
chart.on('customClick'.... should return not only a value of a concrete grouping property, but also for aggregationGroupingProperty. On the screen, you can see when the mouse is over the column of the StackedBar Chart, we can see bothly the yellow and blue rectangles data. But when I'm searching a customClick Event, there is no data of aggregationGropuping. I can see inside of the first argument of the customClick function the Key "Ложь", but for me it is important also to fetch "Пол2" or "Пол3" in dependence of where certainly I'm clicked - on the "Пол2" or on the "Пол3".

Inside of the column, I expect that I can click on the different rectangles and fetch the property to select it from the all chart column data.

## Difference from Current Behavior
When I'm clicking on the yellow rectangle, I'm getting as "Пол2", so as "Пол3" data. I can't separate it. I don't know, am I clicked on "Пол2" or on the "Пол3".

## Possible Implementation
There should be some property to know, where sertainly I'm clicked inside of the one chart stacked column.

## Example Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/7087581/96098198-83184f80-0eda-11eb-9f81-839ff54b03c5.png)
![image](https://user-images.githubusercontent.com/7087581/96098978-6597b580-0edb-11eb-9bea-52cfcd03747e.png)

**Comment by DalerAsrorov** [comment]
I see what you mean Eugene - this is a reasonable feature to ask. I just marked it as `Ready to Go` if current contributors have some sparring time to work on it. I may hop on in the next few days.

**Comment by Lennen** [comment]
but can I make something without using the CustomClick from the Britecharts? Can I solve it using the JS or my own code?

**Comment by Lennen** [comment]
> I see what you mean Eugene - this is a reasonable feature to ask. I just marked it as `Ready to Go` if current contributors have some sparring time to work on it. I may hop on in the next few days.
> 
> General idea is to be able to retrieve the data point of the sub-bar that belongs to the major bar of the chart on `customClick` event.

But can I make something there without using the CustomClick from the Britecharts? Can I solve it using the JS, my own code?

**Comment by Golodhros** [comment]
> > I see what you mean Eugene - this is a reasonable feature to ask. I just marked it as `Ready to Go` if current contributors have some sparring time to work on it. I may hop on in the next few days.
> > General idea is to be able to retrieve the data point of the sub-bar that belongs to the major bar of the chart on `customClick` event.
> 
> But can I make something there without using the CustomClick from the Britecharts? Can I solve it using the JS, my own code?

In theory, yes. It could get tricky though!

**Comment by Golodhros** [comment]
Done in 3.0.0 by #1051. `customClick` on the stacked bar (and the grouped bar) fires only when a bar is clicked and passes the clicked bar's own data as a third argument after the column and the pointer position: for the stacked bar the stack's name, its value and the column's key; for the grouped bar the bar's entry.
