### ISSUE TITLE
Update to D3.js V6

### ISSUE THREAD

**Issue by Golodhros** [britecharts/britecharts#886]
## Expected Behavior
Britecharts should be up to date with the latest version of D3.js

## Difference from Current Behavior
We are in V5

## Possible Implementation
There is a migration guide: https://observablehq.com/d/f91cccf0cad5e9cb
And the changelog https://github.com/d3/d3/blob/master/CHANGES.md

## Context
It will be important to signal that the library is up to date and with future

**Comment by johnrichardrinehart** [comment]
Is this project still under active development? I'm interested in helping address some issues and bring `britecharts` up-to-date, but @Golodhros you seem to be the primary maintainer. Are you able to offer support if I help resolve issues like this?

**Comment by Golodhros** [comment]
> Is this project still under active development? 

Totally! We are hard at work with the V3! Check out our RC candidate https://github.com/britecharts/britecharts/tree/release/3.0.0-rc3 and out short-term roadmap to get there (https://github.com/britecharts/britecharts/issues/870)

> I'm interested in helping address some issues and bring `britecharts` up-to-date, but @Golodhros you seem to be the primary maintainer. Are you able to offer support if I help resolve issues like this?

That's awesome! Yes, I will be here to support you if you choose to contribute!

This could be a great ticket to tackle, we didn't plan to include it in V3, so if you get tired of it, it won't affect our roadmap, but it would be awesome to update to v6!!

**Comment by johnrichardrinehart** [comment]
Okay, let's do this. I've forked the repo and I've started to run the tests.

They've been taking a while, though, and I'm not getting any CPU/memory updates. Is there a verbose mode so I can see the status? Are these tests running in a headless browser?

**Comment by Golodhros** [comment]
> Okay, let's do this. I've forked the repo and I've started to run the tests.

Awesome! Please use the [rc3 branch](https://github.com/britecharts/britecharts/tree/release/3.0.0-rc3)!

> They've been taking a while, though, and I'm not getting any CPU/memory updates. Is there a verbose mode so I can see the status? Are these tests running in a headless browser?

Yes, they should run with Karma, so it should pop a new Chrome window.

**Comment by johnrichardrinehart** [comment]
> Awesome! Please use the rc3 branch!

No problem. I'll work off of `3.0.0-rc3/d3v6`.

> Yes, they should run with Karma, so it should pop a new Chrome window.

Oh, weird. I have `Chrome` installed (Ubuntu Desktop 20.10) and on my path. No window popped up. Any ideas? I can dig around, if not.

**Comment by Golodhros** [comment]
> > Yes, they should run with Karma, so it should pop a new Chrome window.
> 
> Oh, weird. I have `Chrome` installed (Ubuntu Desktop 20.10) and on my path. No window popped up. Any ideas? I can dig around, if not.

Interesting, maybe an ubuntu issue? Yeah, if you could dig on that it would be great!

**Comment by Golodhros** [comment]
One thing @johnrichardrinehart, we moved into RC4: https://github.com/britecharts/britecharts/tree/release/3.0.0-rc4

**Comment by IdeaHunter** [comment]
Hi!
d3 V7 released like year ago
what the status of upgrade process?

**Comment by Golodhros** [comment]
Hi @IdeaHunter, thanks for the interest!

Right now we are working hard on the v3 release and a move into a monorepo (check it out in https://github.com/britecharts/britecharts/tree/main). 

I would love to tackle this too, but I am not sure if I can do it for v3 or wait a bit more. It shouldn't be too hard, the changes haven't been large AFAIK.

Any help would be dearly appreciated!

**Comment by IdeaHunter** [comment]
@Golodhros , oh, new version, nice ❤️  How i can try it out, seems no release in npm so far.

**Comment by Golodhros** [comment]
> @Golodhros , oh, new version, nice ❤️ How i can try it out, seems no release in npm so far.

Glad you are excited about it @IdeaHunter!! 
Not published in NPM yet, but you could go to the main branch and run `yarn pack` to get an installable version. 
The new docs are already up on https://britecharts.github.io/britecharts/
