### ISSUE TITLE
Add Y axis format for bar charts

### ISSUE THREAD

**Issue by gsteja2307** [britecharts/britecharts#891]
## Expected Behavior
when the values in the data given are all zeroes , then the y axis labels rendered are decimal values, but user must be able to format it to display only integer values

## Difference from Current Behavior
Currently the graph renders decimals(0,1 ,0.2, 0.4,0.5,0.6,0.8,0.9,1) for the y axis when all the values are 0. 
request: add a function which displays only integers in the y axis (1, 2, 3, 4, 5..) even if all values are 0

## Context
i am using bar chart to display to number of heart disease cases in given hospitals . but when all the values / heart disease counts in all hospitals are 0 , then i dont want to render y -axis in decimals , since heart disease cases are integers and cannot be decimals

**Comment by Golodhros** [comment]
Hi @gsteja2307, thanks for your question!

We actually have that already, it is called '.numberFormat' (https://britecharts.github.io/britecharts/module-Bar.html#.numberFormat__anchor) give it a try using any of the formats on https://observablehq.com/@d3/d3-format and let me know how it goes!

**Comment by gsteja2307** [comment]
![image](https://user-images.githubusercontent.com/30834202/100571399-0b22af00-32f9-11eb-8798-c0e195adf0f1.png)
Hi Golodhros , I have added an image for your reference . 

In image you can see that when my data is empty (all the values are 0) , then when graph is rendered , the Y axis has decimal values . I want it to be only integers .

Using .numberFormat doesnot resolve my issue , please refer to below image
![image](https://user-images.githubusercontent.com/30834202/100571943-5c7f6e00-32fa-11eb-928d-5d57e5bdf619.png)

**Comment by Golodhros** [comment]
Hi @gsteja2307, thanks for following up!

This seems like the expected result. When all values are 0, we render a dummy chart with a base Y axis of 1, so the "empty" values go from 0 to 1. When you add a formatting, that format function rounds the decimal values either to 0 or 1.

I understand you want to specify explicitly the values that will show on that Y scale, right? What is your use case for needing this?

**Comment by gsteja2307** [comment]
> I understand you want to specify explicitly the values that will show on that Y scale, right?
No,
I want the Y-axis to display only the integers as my data consists of only integer values. so as to improve user interaction and Usability .
> This seems like the expected result. When all values are 0, we render a dummy chart with a base Y axis of 1, so the "empty" values go from 0 to 1.
can we have a feature to let user render Y scale  in integers (Y scale = 1 to 10)

**Comment by gsteja2307** [comment]
> I understand you want to specify explicitly the values that will show on that Y scale, right?

No,
I want the Y-axis to display only the integers as my data consists of only integer values. so as to improve user interaction and Usability .

> This seems like the expected result. When all values are 0, we render a dummy chart with a base Y axis of 1, so the "empty" values go from 0 to 1.

can we have a feature to let user render dummy chart with a base Y axis of 10 (Y scale = 0 to 10(this is just a magical number))
when the graph is empty?

**Comment by Golodhros** [comment]
> > I understand you want to specify explicitly the values that will show on that Y scale, right?
> 
> No,
> I want the Y-axis to display only the integers as my data consists of only integer values. so as to improve user interaction and Usability .

Well, at this point your data is empty, so the chart doesn't know what the values would be.

> can we have a feature to let user render dummy chart with a base Y axis of 10 (Y scale = 0 to 10(this is just a magical number))
> when the graph is empty?

This is what I just mentioned, you want to specify explicitly the values that will show on the empty chart Y axis.

I understand this request, but I see it as a very specific request that won't add a lot of value to the library while increasing the complexity of the code.

However, you could play with the 'percentageAxisToMaxRatio ' and see if setting it to a high enough value you get what you want.
