### ISSUE TITLE
Bar chart grouping data columns with same name

### ISSUE THREAD

**Issue by havardl** [britecharts/britecharts#902]
I'm trying to make a simple horizontal graph with top 15 occurrences. The problem is that one named thing can occur multiple times in the data set and that seems to lead the Bar component to group all the values together in on bar. 

From the data below, I would expect to see 4 bars. Instead I get 3 bars, where the first bar is grouped with values from the first and last object.

```javascript
const barData = [
  { id: 1, name: "Thing 1", value: 842 },
  { id: 2, name: "Thing 2", value: 529 },
  { id: 3, name: "Thing 3", value: 477 },
  { id: 4, name: "Thing 1", value: 47 },
];      
```

I tried to ad an id, but from [reading the documentation](http://britecharts.github.io/britecharts/global.html#BarChartData), it seems a Bar object only accepts an array of objects with `name` and `value` fields?

**Comment by Golodhros** [comment]
Hi @havardl, thanks for your question!

Interesting, we never though of something like this. Yes, the bar chart doesn't use ids, we assumed all the names would be unique.

Could you expand a bit on your use case? Why is there a repeated name? How would your users differentiate between them?

**Comment by havardl** [comment]
Hi @Golodhros, thanks for the fast reply!

Basically, it's a weekly update on activity from unique members. But, a member could have more than one activity registered that week, and so I would like to show multiple activities for the same member - but with different values. 

If I could assign a unique id to each object (like my data snippet) to separate each bar and then show the `name` field as normal, that would fulfill my need.

**Comment by Golodhros** [comment]
I see, makes sense.

However, I feel this use case is pretty specific, so I don't think we will support this feature in the short term.

I can think on different ways you could work around this:
- Not sure if this would work, but you could try to add an empty space after the duplicated labels, AFAIK we don't trim the strings on the names
- Another option would be to add prefixes, so maybe using a name like `member: Thing 1` 
- The last resort would be for you to fork britecharts and modify the bar chart so it uses ids as the main identification for the bars

I am sorry I cannot give you a better solution!

**Comment by havardl** [comment]
Agreed, I think I can find a way around the limitations. Thanks for the suggestions!

**Comment by Golodhros** [comment]
Happy to help!
