### ISSUE TITLE
Treemap support

### ISSUE THREAD

**Issue by davidm49090** [britecharts/britecharts#924]
Hello,

I love your library. Could you please create an implementation for treemaps?

They have a certain grace for representing proportions that pie charts just don't have.

**Comment by davidm49090** [comment]
I saw this issue is closed... Should I give up on my dream of treemaps with this library?

**Comment by Golodhros** [comment]
> I saw this issue is closed... Should I give up on my dream of treemaps with this library?

Oh, not really!
We are changing the way we manage the issues, all that are triaged will be closed, but with the "needs votes" label, so you can +1 to it. This will create a ranking and show what is more needed by the community!

**Comment by davidm49090** [comment]
+1

**Comment by Golodhros** [comment]
> +1

Oh, you need to click on the emoji of the issue and hit the +1 there!

**Comment by davidm49090** [comment]
OK. Just gave it a thumbs up.
