### ISSUE TITLE
Line Chart: Custom Line issues

### ISSUE THREAD

**Issue by portalinside** [britecharts/britecharts#935]
## Expected Behavior

dfunction drawCustomLine should correct refresh the line and the text.

## Current Behavior

You append always „text“ and if you resize/redraw the Chart the text in „name“ isn’t remove, so you draw the „name“ value multiple time.

            for(let line of customLines) {
                if (line.name) {
                    svg.select('.custom-lines-group')
                        .append('text‘)   //if text doesn’t exist than  append
                        .attr('x', chartWidth)
                        .attr('y', yScale(line.y) - 6)
                        .attr('class', 'custom-line-annotation')
                        .attr('text-anchor', 'end')
                        .attr('dominant-baseline', 'baseline')
                        .text(line.name);
                }
            }

## Possible Solution

.append('text‘)   //if text doesn’t exist than  append

## Steps to Reproduce

1.  Write Code with above function an resize/refresh custom line
2.
3.
4.

## Your Environment

* Britecharts version used: 2.18.0
* Browser Name and version: all browser chrome etc.
* Operating System and version: mac os
* Link to your project or codepen:

**Comment by Golodhros** [comment]
Hi @portalinside, thanks for taking the time to open an issue!

That is right, I have seen this happening on the line chart. Here is the fix: https://github.com/britecharts/britecharts/pull/937

After merging it, I will publish it on the v3 rc6

**Comment by portalinside** [comment]
Hi Marcos,

thanks for the info.

Here are the next issues. I hope it is helpful.

1) Legend is not responsive. Is not center to the middle on Chart width.
2) Vertical Grid on x= 0 isn’t drawed
3) Value x= 1 isn’t drawed
4) x-Line is drawed in negativ range. It should be started ab Pos=0
5) How /which API Function can call to reset the chartbrush?



Greetings
Andreas

**Comment by Golodhros** [comment]
Hi Andreas,

1) Legend is not responsive. Is not center to the middle on Chart width.
The legend is a component that renders independently, so you would use html and css to create a container for it and position it, then you would render the legend within that container.

2) Vertical Grid on x= 0 isn’t drawed
That could be a bug

3) Value x= 1 isn’t drawed
It could be a bug, could you try to replicate it on a codepen? You can start here: https://codepen.io/Britecharts/pen/PxvZBJ

4) x-Line is drawed in negativ range. It should be started ab Pos=0
That sounds like a possible bug too, the negative values were recently contributed and it could be that they didn't test them  thoroughly

5) How /which API Function can call to reset the chartbrush?
There is no function. In general,  you would store the original data for line and brush and use it again when a "Reset" button is pressed.


It would be lovely if you could create a ticket for the above bugs and even better if you can provide reproductions on Codepen links, that way I would be able to fix them soon!

Thanks for taking the time!

**Comment by Golodhros** [comment]
Reviewed some of the issues, it seems they are OK.
