### ISSUE TITLE
Loading State for Bullet Chart

### ISSUE THREAD

**Issue by Golodhros** [britecharts/britecharts#940]
## Expected Behavior

Our bullet charts should have a loading state

## Difference from Current Behavior

They don't have

## Possible Implementation

A simple square would probably work at first

**Comment by sagarchoudhary96** [comment]
@Golodhros  can i pick this up?

**Comment by harshmathurx** [comment]
I'd like to help

**Comment by Golodhros** [comment]
Awesome! This is up for grabs definitely!

The first thing we need is an SVG drawing that resembles a bit the final bullet chart, and that it has a similar aspect ratio. I am imagining just one rectangular box and a thick line on top of it.

Then, we'll need to add it as markup on the "load" helper. Then, following the code on https://github.com/britecharts/britecharts/pull/939 we will add it as a loading state for the bullet chart. Mind that we need to work over the rc5 branch, not on master!!
