### ISSUE TITLE
Refactor Grid Lines to use new Grid helper

### ISSUE THREAD

**Issue by Golodhros** [britecharts/britecharts#947]
## Expected Behavior
We should be using the new grid helper to render the grid lines on the whole library

## Difference from Current Behavior
We are manually creating gridlines in the following charts:
- Grouped bar chart
- Line chart
- Scatter plot
- Stacked area chart
- Stacked bar chart

## Possible Implementation
Check the implementation in the bar chart

## Context
This will reduce code and duplication

**Comment by Golodhros** [comment]
Is there anything left to do on this one @jayeclark?

**Comment by jayeclark** [comment]
I think this one is all set!
