### ISSUE TITLE
Make an Accessibility Audit

### ISSUE THREAD

**Issue by Golodhros** [britecharts/britecharts#955]
## Expected Behavior
We should try to cover at least the most basic a11y features for our charts.

## Difference from Current Behavior
Right now we don't do anything on a11y.

## Possible Implementation
Research needed here.

**Comment by azemetre** [comment]
Hello! If you need help I'm willing to assist in coming up with an audit plan. If it meets your needs, I can run the audit myself.

I see there's a "kitchen sink" demo in the docs, would auditing this piece be representative of the entire library? At least for the first pass at inspecting accessibility?

**Comment by Golodhros** [comment]
Hi @azemetre,
that is awesome!! We would love your help on assessing our current a11y level!

Instead of the Kitchen Sink, I would start by checking all the demos one by one instead. One large caveat is that we are almost done with Version 3 that brings a good chunk of changes, so it would be advisable us to check [the code in the release/3.0.0-rc6](https://github.com/britecharts/britecharts/tree/release/3.0.0-rc6) branch.

Thanks again!!

**Comment by azemetre** [comment]
Awesome, I can come up with something the next few days and post it in this thread. Thanks for the tip on using v3.0.0.

**Comment by Golodhros** [comment]
Thank you @azemetre!!

**Comment by azemetre** [comment]
Sorry for the delay, things have been hectic in my personal life. Still plan on completing it hopefully this Sunday.
