### ISSUE TITLE
Time series data on Bar Chart

### ISSUE THREAD

**Issue by fk1blow** [britecharts/britecharts#973]
Have a large dataset, spanning 2 years(it can be larger) and the labels for each value(label: Date, value: number), will simply overlap and pile up, making them impossible to read or distinguish.

## Expected Behavior
Should sample only one month, skipping days; screenshot to how another chart library renders the same dataset
![image](https://user-images.githubusercontent.com/106429/142459883-ac3b0215-4e97-4615-b8f6-de0117f7548c.png)

## Difference from Current Behavior
cannot specify

## Example Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/106429/142458863-25696e87-d719-449c-8e70-288f89ea3571.png)

## Context
We need this improvement b/c without it, for large datasets, britecharts would be unusable

**Comment by Golodhros** [comment]
Hi @fk1blow, thanks for creating this issue!

I see that you are using a bar chart with a time series dataset. We do have a configuration for selecting what time frame to show on the ticks on other charts that were supposed to chart time series data (Linechart and Stackedarea) but we don't have it on the Bar chart for now.

I think adding support to the bar chart to have time series is something that makes sense and we can add into the backlog. 

If you want to chart this info right now, I will suggest you to try the line chart and stacked area though.

**Comment by Golodhros** [comment]
Actually, if you use the LineChart and set the 'lineCurve' option to 'step', you might get something really similar to what you are looking for.

**Comment by fk1blow** [comment]
@Golodhros thanks for taking the time!
Will try your suggestion and see where that goes.

**Comment by Golodhros** [comment]
> @Golodhros thanks for taking the time! Will try your suggestion and see where that goes.

Happy to help!
Try also the stacked area chart areaCurve, you might prefer it if you want the bottom part of the line to be filled
