### ISSUE TITLE
Cannot set locale on a line chart

### ISSUE THREAD

**Issue by fk1blow** [britecharts/britecharts#979]
Want to have the ability to change the locale, between 'en-US' and 'da-DK', on a line chart's axis' label

## Expected Behavior
should display the date formatted according to the selected locale

## Difference from Current Behavior
---

## Example Screenshots (if appropriate):

![image](https://user-images.githubusercontent.com/106429/151024039-548ecc39-834b-4048-83d6-6cb059eea5f2.png)

## Context
need to format the dates based on the user's current selected language.

Was able to format the tooltips and saw the docs section about `locale`set/get, but keep getting a `localeTimeMap is not defined`

Code used to configure the line chart:

```js
chart.
        .lineCurve('basis')
        .grid('horizontal')
        .locale('da-DK')
```

also tried with multiple locale values(eg: 'ru-RU' or 'en-US') but still get the error.

edit 1:

is the `localeTimeMap` inside d3 itself? 
https://github.com/britecharts/britecharts/blob/59eafff49306544a3f29f389d6a4680458948335/src/charts/helpers/date.js#L47
nvm, it s here https://github.com/britecharts/britecharts/blob/8447ded5575864f5527afc2884d1bdb5509c971e/src/charts/helpers/axis.js

**Comment by fk1blow** [comment]
sry, forgot to mention,
`"britecharts": "^2.18.0"`

**Comment by fk1blow** [comment]
ohhhk, i ll give it a go.

Thanks for the help!

**Comment by Golodhros** [comment]
Closing for now until more news.
